"use client";
import { useMemo, useState } from "react";
import { buildWhatsAppOutreach, calculateSalesMetrics, generateProposal, salesPackages } from "@pageloom/core";
import { CalendarDays, Check, Copy, FileSignature, MessageCircleMore } from "lucide-react";
import { Button, Card, PageHeader, Stat, money } from "@/components/product-ui";
import { useOrganization } from "@/lib/organization";
import { useLiveCollection } from "@/lib/live-data";
import { ClosingWorkspace } from "@/components/closing-workspace";
type Lead = { id: string; name: string; company: string; status?: string; stage: string; value: number; nextCallAt?: string };
export default function SalesEnablementPage() { const { organizationId } = useOrganization(), leads = useLiveCollection<Lead>(organizationId ? `organizations/${organizationId}/leads` : undefined), metrics = calculateSalesMetrics(leads.data.map(lead => ({ status: lead.status ?? lead.stage, value: lead.value, nextCallAt: lead.nextCallAt }))); return <div className="space-y-6"><PageHeader eyebrow="SALES ENABLEMENT" title="Customer acquisition" description="Move prospects from a relevant conversation to a booked call, clear proposal, selected package, and paid onboarding."/><div className="grid grid-cols-2 gap-3 xl:grid-cols-4"><Stat label="Leads" value={metrics.leads} note="Total pipeline"/><Stat label="Scheduled calls" value={metrics.calls} note="Upcoming conversations"/><Stat label="Conversion rate" value={`${metrics.conversionRate}%`} note="Leads converted to won"/><Stat label="Revenue" value={money(metrics.revenue)} note="Won pipeline value" tone="positive"/></div><Outreach/><SalesFlow/><ClosingWorkspace/></div>; }
function Outreach() { const [context, setContext] = useState({ firstName: "", businessName: "", observation: "", bookingUrl: "" }), [copied, setCopied] = useState<string>(); const ready = Object.values(context).every(value => value.trim()), steps = useMemo(() => ready ? buildWhatsAppOutreach(context) : [], [context, ready]); async function copy(id: string, message: string) { await navigator.clipboard.writeText(message); setCopied(id); window.setTimeout(() => setCopied(undefined), 1500); } return <section className="space-y-4"><Card><div className="flex items-center gap-3"><span className="icon-box"><MessageCircleMore className="h-4 w-4"/></span><div><h2 className="text-sm font-semibold">WhatsApp outreach flow</h2><p className="mt-1 text-xs text-[var(--muted)]">Personalize once, then use a respectful four-touch sequence.</p></div></div><div className="mt-5 grid gap-3 md:grid-cols-2"><Field label="First name" value={context.firstName} set={firstName => setContext({ ...context, firstName })}/><Field label="Business" value={context.businessName} set={businessName => setContext({ ...context, businessName })}/><Field label="Relevant observation" value={context.observation} set={observation => setContext({ ...context, observation })}/><Field label="Booking URL" value={context.bookingUrl} set={bookingUrl => setContext({ ...context, bookingUrl })}/></div></Card>{ready && <div className="grid gap-4 lg:grid-cols-2">{steps.map(step => <Card key={step.id}><div className="flex items-start justify-between gap-3"><div><span className="eyebrow">DAY {step.delayDays}</span><h2 className="mt-2 text-sm font-semibold">{step.purpose}</h2></div><Button variant="secondary" onClick={() => void copy(step.id, step.message)}>{copied === step.id ? <Check className="h-4 w-4"/> : <Copy className="h-4 w-4"/>}{copied === step.id ? "Copied" : "Copy"}</Button></div><p className="mt-5 rounded-xl bg-[#fafaf8] p-4 text-xs leading-6">{step.message}</p></Card>)}</div>}</section>; }
function SalesFlow() { const [form, setForm] = useState({ prospectName: "", businessName: "", challenge: "", packageId: "growth" as "launch"|"growth"|"authority", validUntil: "", callAt: "" }), [proposal, setProposal] = useState(""); function create(event: React.FormEvent) { event.preventDefault(); setProposal(generateProposal(form)); } return <section className="grid gap-4 xl:grid-cols-2"><Card><div className="flex items-center gap-3"><span className="icon-box"><CalendarDays className="h-4 w-4"/></span><div><h2 className="text-sm font-semibold">Call and package selection</h2><p className="mt-1 text-xs text-[var(--muted)]">Capture the commercial decision before generating the proposal.</p></div></div><form className="mt-5 grid gap-3 md:grid-cols-2" onSubmit={create}><Field label="Prospect" value={form.prospectName} set={prospectName => setForm({ ...form, prospectName })}/><Field label="Business" value={form.businessName} set={businessName => setForm({ ...form, businessName })}/><label className="field md:col-span-2"><span>Primary challenge</span><textarea required className="input min-h-24" value={form.challenge} onChange={event => setForm({ ...form, challenge: event.target.value })}/></label><label className="field"><span>Scheduled call</span><input required type="datetime-local" className="input" value={form.callAt} onChange={event => setForm({ ...form, callAt: event.target.value })}/></label><label className="field"><span>Proposal valid until</span><input required type="date" className="input" value={form.validUntil} onChange={event => setForm({ ...form, validUntil: event.target.value })}/></label><div className="md:col-span-2 grid gap-2 md:grid-cols-3">{salesPackages.map(item => <button type="button" key={item.id} onClick={() => setForm({ ...form, packageId: item.id })} className={`rounded-xl border p-4 text-start ${form.packageId === item.id ? "border-[#7357ff] bg-[#f7f5ff]" : "border-[var(--border)]"}`}><b className="text-xs">{item.name}</b><strong className="mt-2 block text-lg">{money(item.price)}</strong><small className="text-[9px] text-[var(--muted)]">{item.timelineWeeks} weeks</small></button>)}</div><Button className="md:col-span-2" type="submit"><FileSignature className="h-4 w-4"/>Generate proposal</Button></form></Card><Card><h2 className="text-sm font-semibold">Proposal preview</h2>{proposal ? <pre className="mt-4 whitespace-pre-wrap rounded-xl bg-[#fafaf8] p-4 font-sans text-xs leading-6">{proposal}</pre> : <p className="mt-4 text-xs text-[var(--muted)]">Complete the call, package, and proposal details to produce a customer-ready summary.</p>}</Card></section>; }
function Field({ label, value, set }: { label: string; value: string; set: (value: string) => void }) { return <label className="field"><span>{label}</span><input required className="input" value={value} onChange={event => set(event.target.value)}/></label>; }
