"use client";
import Link from "next/link";
import { useCallback, useEffect, useState } from "react";
import { CheckCircle2, ClipboardCheck, RotateCcw, XCircle } from "lucide-react";
import { api } from "@/lib/api";
import { Button, Card, CardHeader, Empty, Status, dateTime } from "./product-ui";
import { t } from "@/lib/i18n";
type Submission={id:string;organizationId:string;organizationName:string;customerId:string;projectId:string;websiteId:string;websiteName:string;submittedBy:string;submittedAt:string;fieldIds:string[]};
export function ContentApprovalCenter(){const s=t("contentApprovalCenter"),c=t("common");const[items,setItems]=useState<Submission[]>([]),[busy,setBusy]=useState(""),[error,setError]=useState("");const load=useCallback(async()=>{try{setItems(await api<Submission[]>("/platform/content-submissions"));setError("")}catch(failure){setError(failure instanceof Error?failure.message:s.loadError)}},[s.loadError]);useEffect(()=>{let active=true;(async()=>{try{const result=await api<Submission[]>("/platform/content-submissions");if(active){setItems(result);setError("")}}catch(failure){if(active)setError(failure instanceof Error?failure.message:s.loadError)}})();return()=>{active=false}},[s.loadError]);async function decide(item:Submission,decision:"approved"|"rejected"|"changes_requested"){const reason=decision==="approved"?undefined:window.prompt(decision==="rejected"?s.rejectionReasonPrompt:s.changesRequestedPrompt);if(decision!=="approved"&&!reason?.trim())return;setBusy(`${item.organizationId}-${item.websiteId}`);try{await api(`/projects/${item.projectId}/website-content/decision`,{method:"POST",body:JSON.stringify({organizationId:item.organizationId,decision,reason})});await load()}catch(failure){setError(failure instanceof Error?failure.message:s.decisionError)}finally{setBusy("")}}return <Card><CardHeader icon={ClipboardCheck} title={s.title} subtitle={s.subtitle}/>{items.length?<div className="space-y-3">{items.map(item=>{const key=`${item.organizationId}-${item.websiteId}`;return <article className="rounded-xl border border-[var(--border)] p-4" key={key}><div className="flex flex-wrap items-start justify-between gap-3"><span><b className="block text-xs">{item.websiteName}</b><small className="mt-1 block text-[9px] text-[var(--muted)]">{item.organizationName} · {s.customerLabel(item.customerId)} · {dateTime(item.submittedAt)} · {s.submittedByLabel(item.submittedBy)}</small></span><Status value="pending" label={s.pendingStatusLabel}/></div><p className="mt-3 text-[10px] text-[var(--muted)]">{s.changedFieldsLabel(item.fieldIds)}</p><div className="mt-4 flex flex-wrap gap-2"><Link className="button button-secondary" href={`/master/content?organizationId=${encodeURIComponent(item.organizationId)}&projectId=${encodeURIComponent(item.projectId)}`}>{s.previewLink}</Link><Button disabled={busy===key} onClick={()=>void decide(item,"approved")}><CheckCircle2 className="h-3.5 w-3.5"/>{s.approveAndPublishButton}</Button><Button variant="secondary" disabled={busy===key} onClick={()=>void decide(item,"changes_requested")}><RotateCcw className="h-3.5 w-3.5"/>{s.returnForChangesButton}</Button><Button variant="danger" disabled={busy===key} onClick={()=>void decide(item,"rejected")}><XCircle className="h-3.5 w-3.5"/>{c.reject}</Button></div></article>})}</div>:<Empty title={error?s.emptyTitleError:s.emptyTitle} description={error||s.emptyDescription}/>}</Card>}
