"use client";
import {useMemo,useState} from "react";
import {usePathname} from "next/navigation";
import {KeyRound} from "lucide-react";
import {api} from "@/lib/api";
import {useLiveCollection} from "@/lib/live-data";
import {useOrganization} from "@/lib/organization";
import {Button,Card,CardHeader} from "./product-ui";
type Customer={id:string;businessName:string;status:string;updatedAt:string};
export function CustomerPortalAccess(){const pathname=usePathname(),{organizationId,membership}=useOrganization(),customers=useLiveCollection<Customer>(pathname==="/crm"&&organizationId?`organizations/${organizationId}/customers`:undefined);const[customerId,setCustomerId]=useState(""),[email,setEmail]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState("");const selected=useMemo(()=>customerId||customers.data[0]?.id||"",[customerId,customers.data]);if(pathname!=="/crm"||!membership||!["owner","admin"].includes(membership.role))return null;async function createInvitation(){if(!selected||!email)return;setBusy(true);setMessage("");try{const result=await api<{email:string;expiresAt:string}>(`/customers/${selected}/invitations`,{method:"POST",body:JSON.stringify({organizationId,email})});setMessage(`Access is ready for ${result.email} until ${new Intl.DateTimeFormat("en",{dateStyle:"medium"}).format(new Date(result.expiresAt))}. Ask the customer to sign in with this verified Google email.`);setEmail("")}catch(error){setMessage(error instanceof Error?error.message:"Invitation failed")}finally{setBusy(false)}}return <Card className="mb-7"><CardHeader icon={KeyRound} title="Customer portal access" subtitle="Grant a verified customer email access only to its own projects and files"/><div className="grid gap-3 md:grid-cols-[1fr_1fr_auto]"><label className="field"><span>Customer</span><select value={selected} onChange={event=>setCustomerId(event.target.value)} disabled={customers.loading}>{customers.data.map(customer=><option key={customer.id} value={customer.id}>{customer.businessName}</option>)}</select></label><label className="field"><span>Customer Google email</span><input type="email" autoComplete="email" value={email} onChange={event=>setEmail(event.target.value)} placeholder="customer@business.com"/></label><Button className="self-end" disabled={busy||!selected||!email} onClick={()=>void createInvitation()}>{busy?"Preparing…":"Create access"}</Button></div>{message&&<p className="mt-3 text-xs text-[var(--muted)]" role="status">{message}</p>}</Card>}
