"use client";
import { Bell, CheckCheck } from "lucide-react";
import { api } from "@/lib/api";
import { useLiveCollection } from "@/lib/live-data";
import { useOrganization } from "@/lib/organization";
import { Button, Card, CardHeader, Empty, dateTime } from "./product-ui";
import { t } from "@/lib/i18n";
type Notification = { id: string; title: string; body?: string; severity?: string; read?: boolean; createdAt: string };
export function NotificationInbox() { const s = t("notificationInbox"); const { organizationId } = useOrganization(), notifications = useLiveCollection<Notification>(organizationId ? `organizations/${organizationId}/notifications` : undefined, "createdAt", 100), unread = notifications.data.filter(item => !item.read); async function read(id: string) { await api(`/notifications/${id}/read`, { method: "PATCH", body: JSON.stringify({ organizationId }) }); } async function readAll() { await api("/notifications-read-all", { method: "PATCH", body: JSON.stringify({ organizationId }) }); } return <Card><CardHeader icon={Bell} title={s.title} subtitle={s.subtitle} action={unread.length ? <Button variant="secondary" onClick={() => void readAll()}><CheckCheck className="h-3.5 w-3.5" />{s.acknowledgeAll}</Button> : undefined} />{unread.length ? <div className="grid gap-2 md:grid-cols-2">{unread.map(item => <button className="rounded-xl border border-[var(--border)] p-3 text-start hover:bg-[#fafaf8]" onClick={() => void read(item.id)} key={item.id}><div className="flex items-start justify-between gap-3"><b className="text-[10px]">{item.title}</b><span className={`h-2 w-2 rounded-full ${item.severity === "critical" ? "bg-red-500" : "bg-amber-500"}`} /></div>{item.body && <p className="mt-1 text-[9px] leading-4 text-[var(--muted)]">{item.body}</p>}<small className="mt-2 block text-[8px] text-[var(--muted)]">{dateTime(item.createdAt)} · {s.ackHint}</small></button>)}</div> : <Empty title={s.emptyTitle} description={s.emptyDescription} />}</Card> }
