"use client";
import { useState } from "react";
import { KeyRound, UserPlus } from "lucide-react";
import { api } from "@/lib/api";
import { Button, Card, CardHeader, Empty } from "./product-ui";
type Item={id:string;name?:unknown;email?:unknown;permissions?:unknown};
type Permissions={contentEdit:boolean;support:boolean;comments:boolean;assets:boolean};
const defaults:Permissions={contentEdit:true,support:true,comments:true,assets:true};
export function PortalUserManager({organizationId,customerId,projects,websites,users,onChanged}:{organizationId:string;customerId:string;projects:Item[];websites:Item[];users:Item[];onChanged:()=>Promise<void>}){const[email,setEmail]=useState(""),[projectIds,setProjects]=useState<string[]>([]),[websiteIds,setWebsites]=useState<string[]>([]),[permissions,setPermissions]=useState(defaults),[busy,setBusy]=useState(""),[message,setMessage]=useState("");async function invite(){setBusy("invite");setMessage("");try{await api(`/admin/customers/${customerId}/portal-users/invite`,{method:"POST",body:JSON.stringify({organizationId,email,projectIds,websiteIds,permissions})});setEmail("");setMessage("Secure portal invitation created. The verified email can claim access on sign-in.");await onChanged()}catch(failure){setMessage(failure instanceof Error?failure.message:"Invitation failed.")}finally{setBusy("")}}async function update(user:Item,next:Permissions){setBusy(user.id);try{await api(`/admin/customers/${customerId}/portal-users/${user.id}/permissions`,{method:"PATCH",body:JSON.stringify({organizationId,permissions:next})});await onChanged()}catch(failure){setMessage(failure instanceof Error?failure.message:"Permissions update failed.")}finally{setBusy("")}}return <Card><CardHeader icon={UserPlus} title="Invite and permission management" subtitle="Scope verified customer identities to selected projects, websites, and portal capabilities"/><div className="grid gap-4 lg:grid-cols-2"><section><label className="field"><span>Verified customer email</span><input className="input" type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><ChoiceList title="Assigned projects" items={projects} selected={projectIds} setSelected={setProjects}/><ChoiceList title="Assigned websites" items={websites} selected={websiteIds} setSelected={setWebsites}/><PermissionChoices value={permissions} onChange={setPermissions}/><Button className="mt-4" disabled={!email||busy==="invite"} onClick={()=>void invite()}><KeyRound className="h-4 w-4"/>{busy==="invite"?"Creating invitation…":"Create scoped invitation"}</Button></section><section><b className="text-[10px]">Existing portal user permissions</b>{users.length?<div className="mt-3 space-y-3">{users.map(user=>{const value={...defaults,...(user.permissions as Partial<Permissions>|undefined)};return <div className="rounded-xl border border-[var(--border)] p-3" key={user.id}><b className="block text-[10px]">{String(user.email??user.id)}</b><PermissionChoices value={value} onChange={next=>void update(user,next)} disabled={busy===user.id}/></div>})}</div>:<Empty title="No portal users" description="Create a scoped invitation to add the first customer user."/>}</section></div>{message&&<p className="notice notice-success" role="status">{message}</p>}</Card>}
function ChoiceList({title,items,selected,setSelected}:{title:string;items:Item[];selected:string[];setSelected:(value:string[])=>void}){return <fieldset className="mt-4"><legend className="text-[10px] font-semibold">{title}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{items.map(item=><label className="flex items-center gap-2 rounded-lg border border-[var(--border)] p-2 text-[10px]" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(event.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{String(item.name??item.id)}</label>)}</div><small className="text-[8px] text-[var(--muted)]">No selection grants access to all projects or websites belonging to this customer.</small></fieldset>}
function PermissionChoices({value,onChange,disabled=false}:{value:Permissions;onChange:(value:Permissions)=>void;disabled?:boolean}){return <div className="mt-3 grid grid-cols-2 gap-2">{(["contentEdit","support","comments","assets"]as const).map(key=><label className="flex items-center gap-2 text-[9px]" key={key}><input type="checkbox" disabled={disabled} checked={value[key]} onChange={event=>onChange({...value,[key]:event.target.checked})}/>{key.replace(/([A-Z])/g," $1")}</label>)}</div>}
