"use client";
import { useState } from "react";
import { KeyRound, UserPlus } from "lucide-react";
import { api } from "@/lib/api";
import { t } from "@/lib/i18n";
import { Button, Card, CardHeader, Empty } from "./product-ui";
type Item={id:string;name?:unknown;email?:unknown;permissions?:unknown};
type Permissions={contentEdit:boolean;support:boolean;comments:boolean;assets:boolean};
const defaults:Permissions={contentEdit:true,support:true,comments:true,assets:true};
export function PortalUserManager({organizationId,customerId,projects,websites,users,onChanged}:{organizationId:string;customerId:string;projects:Item[];websites:Item[];users:Item[];onChanged:()=>Promise<void>}){const[email,setEmail]=useState(""),[projectIds,setProjects]=useState<string[]>([]),[websiteIds,setWebsites]=useState<string[]>([]),[permissions,setPermissions]=useState(defaults),[busy,setBusy]=useState(""),[message,setMessage]=useState("");const s=t("portalUserManager");async function invite(){setBusy("invite");setMessage("");try{await api(`/admin/customers/${customerId}/portal-users/invite`,{method:"POST",body:JSON.stringify({organizationId,email,projectIds,websiteIds,permissions})});setEmail("");setMessage(s.invitationCreated);await onChanged()}catch(failure){setMessage(failure instanceof Error?failure.message:s.invitationFailed)}finally{setBusy("")}}async function update(user:Item,next:Permissions){setBusy(user.id);try{await api(`/admin/customers/${customerId}/portal-users/${user.id}/permissions`,{method:"PATCH",body:JSON.stringify({organizationId,permissions:next})});await onChanged()}catch(failure){setMessage(failure instanceof Error?failure.message:s.permissionsUpdateFailed)}finally{setBusy("")}}return <Card><CardHeader icon={UserPlus} title={s.title} subtitle={s.subtitle}/><div className="grid gap-4 lg:grid-cols-2"><section><label className="field"><span>{s.emailLabel}</span><input className="input" type="email" value={email} onChange={event=>setEmail(event.target.value)}/></label><ChoiceList title={s.assignedProjects} items={projects} selected={projectIds} setSelected={setProjects} hint={s.noSelectionHint}/><ChoiceList title={s.assignedWebsites} items={websites} selected={websiteIds} setSelected={setWebsites} hint={s.noSelectionHint}/><PermissionChoices value={permissions} onChange={setPermissions}/><Button className="mt-4" disabled={!email||busy==="invite"} onClick={()=>void invite()}><KeyRound className="h-4 w-4"/>{busy==="invite"?s.creatingInvitation:s.createInvitation}</Button></section><section><b className="text-[10px]">{s.existingUsersTitle}</b>{users.length?<div className="mt-3 space-y-3">{users.map(user=>{const value={...defaults,...(user.permissions as Partial<Permissions>|undefined)};return <div className="rounded-xl border border-[var(--border)] p-3" key={user.id}><b className="block text-[10px]">{String(user.email??user.id)}</b><PermissionChoices value={value} onChange={next=>void update(user,next)} disabled={busy===user.id}/></div>})}</div>:<Empty title={s.noPortalUsersTitle} description={s.noPortalUsersDescription}/>}</section></div>{message&&<p className="notice notice-success" role="status">{message}</p>}</Card>}
function ChoiceList({title,items,selected,setSelected,hint}:{title:string;items:Item[];selected:string[];setSelected:(value:string[])=>void;hint:string}){return <fieldset className="mt-4"><legend className="text-[10px] font-semibold">{title}</legend><div className="mt-2 grid gap-2 sm:grid-cols-2">{items.map(item=><label className="flex items-center gap-2 rounded-lg border border-[var(--border)] p-2 text-[10px]" key={item.id}><input type="checkbox" checked={selected.includes(item.id)} onChange={event=>setSelected(event.target.checked?[...selected,item.id]:selected.filter(id=>id!==item.id))}/>{String(item.name??item.id)}</label>)}</div><small className="text-[8px] text-[var(--muted)]">{hint}</small></fieldset>}
function PermissionChoices({value,onChange,disabled=false}:{value:Permissions;onChange:(value:Permissions)=>void;disabled?:boolean}){const s=t("portalUserManager");return <div className="mt-3 grid grid-cols-2 gap-2">{(["contentEdit","support","comments","assets"]as const).map(key=><label className="flex items-center gap-2 text-[9px]" key={key}><input type="checkbox" disabled={disabled} checked={value[key]} onChange={event=>onChange({...value,[key]:event.target.checked})}/>{s.permissions[key]}</label>)}</div>}
