import {LoaderCircle,type LucideIcon} from "lucide-react";
export function PageHeader({eyebrow,title,description,actions}:{eyebrow:string;title:string;description:string;actions?:React.ReactNode}){return <header className="flex flex-col gap-5 border-b border-[var(--border)] pb-7 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-[var(--text)] md:text-[38px]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{description}</p></div>{actions&&<div className="flex flex-wrap gap-2">{actions}</div>}</header>}
export function Card({children,className="",...props}:React.HTMLAttributes<HTMLElement>){return <section {...props} className={`card ${className}`}>{children}</section>}
export function CardHeader({title,subtitle,icon:Icon,action}:{title:string;subtitle?:string;icon?:LucideIcon;action?:React.ReactNode}){return <div className="mb-5 flex items-start justify-between gap-4"><div className="flex items-center gap-3">{Icon&&<span className="icon-box"><Icon className="h-4 w-4"/></span>}<div><h2 className="text-sm font-semibold">{title}</h2>{subtitle&&<p className="mt-1 text-xs text-[var(--muted)]">{subtitle}</p>}</div></div>{action}</div>}
export function Stat({label,value,note,tone="default"}:{label:string;value:string|number;note?:string;tone?:"default"|"dark"|"positive"}){return <div className={`stat stat-${tone}`}><span>{label}</span><strong>{value}</strong>{note&&<small>{note}</small>}</div>}
export function Status({value}:{value:string}){const tone=["completed","active","executed","healthy"].includes(value)?"ok":["failed","blocked","rejected"].includes(value)?"bad":["running","working","review","awaiting_approval"].includes(value)?"warn":"idle";return <span className={`status status-${tone}`}><i/>{value.replaceAll("_"," ")}</span>}
export function Empty({title,description,icon}:{title:string;description:string;icon?:React.ReactNode}){return <div className="empty"><span className="empty-mark">{icon??"P"}</span><b>{title}</b><p>{description}</p></div>}
export function Loading(){return <div className="grid min-h-48 place-items-center"><LoaderCircle className="h-5 w-5 animate-spin text-[var(--muted)]"/></div>}
export function Button({children,variant="primary",...props}:React.ButtonHTMLAttributes<HTMLButtonElement>&{variant?:"primary"|"secondary"|"danger"}){return <button {...props} className={`button button-${variant} ${props.className??""}`}>{children}</button>}
export function money(value=0,currency="ILS"){return new Intl.NumberFormat("en-US",{style:"currency",currency,maximumFractionDigits:0}).format(value)}
export function dateTime(value?:string){return value?new Intl.DateTimeFormat("en",{dateStyle:"medium",timeStyle:"short"}).format(new Date(value)):"—"}
