import { LoaderCircle, type LucideIcon } from "lucide-react";

export function PageHeader({ eyebrow, title, description, actions }: { eyebrow: string; title: string; description: string; actions?: React.ReactNode }) { return <header className="flex flex-col gap-5 border-b border-[var(--border)] pb-7 md:flex-row md:items-end md:justify-between"><div><p className="eyebrow">{eyebrow}</p><h1 className="mt-2 text-3xl font-semibold tracking-[-.045em] text-[var(--text)] md:text-[38px]">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-[var(--muted)]">{description}</p></div>{actions && <div className="flex flex-wrap gap-2">{actions}</div>}</header>; }
export function Card({ children, className = "", ...props }: React.HTMLAttributes<HTMLElement>) { return <section {...props} className={`card ${className}`}>{children}</section>; }
export function CardHeader({ title, subtitle, icon: Icon, action }: { title: string; subtitle?: string; icon?: LucideIcon; action?: React.ReactNode }) { return <div className="mb-5 flex items-start justify-between gap-4"><div className="flex items-center gap-3">{Icon && <span className="icon-box"><Icon className="h-4 w-4" aria-hidden="true" /></span>}<div><h2 className="text-sm font-semibold">{title}</h2>{subtitle && <p className="mt-1 text-xs text-[var(--muted)]">{subtitle}</p>}</div></div>{action}</div>; }
export function Stat({ label, value, note, tone = "default" }: { label: string; value: string | number; note?: string; tone?: "default" | "dark" | "positive" }) { return <div className={`stat stat-${tone}`}><span>{label}</span><strong>{value}</strong>{note && <small>{note}</small>}</div>; }

const heStatus: Record<string, string> = { completed: "הושלם", active: "פעיל", executed: "בוצע", healthy: "תקין", approved: "אושר", failed: "נכשל", blocked: "ממתין לטיפול", rejected: "נדחה", running: "בביצוע", working: "בעבודה", review: "בבדיקה", awaiting_approval: "ממתין לאישור", awaiting_customer: "ממתין לפעולתכם", planning: "בתכנון", draft: "טיוטה", published: "פורסם", superseded: "הוחלף" };
export function Status({ value, label }: { value: string; label?: string }) { const tone = ["completed", "active", "executed", "healthy", "approved", "published"].includes(value) ? "ok" : ["failed", "blocked", "rejected"].includes(value) ? "bad" : ["running", "working", "review", "awaiting_approval", "awaiting_customer"].includes(value) ? "warn" : "idle"; const rendered = label ?? (typeof document !== "undefined" && document.documentElement.lang === "he" ? heStatus[value] : undefined) ?? value.replaceAll("_", " "); return <span className={`status status-${tone}`}><i aria-hidden="true" />{rendered}</span>; }
export function Empty({ title, description, icon }: { title: string; description: string; icon?: React.ReactNode }) { return <div className="empty"><span className="empty-mark" aria-hidden="true">{icon ?? "P"}</span><b>{title}</b><p>{description}</p></div>; }
export function Loading() { return <div className="grid min-h-48 place-items-center" role="status" aria-label="Loading"><LoaderCircle className="h-5 w-5 animate-spin text-[var(--muted)]" aria-hidden="true" /></div>; }
export function Button({ children, variant = "primary", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary" | "secondary" | "danger" }) { return <button {...props} className={`button button-${variant} ${props.className ?? ""}`}>{children}</button>; }
export function money(value = 0, currency = "ILS") { return new Intl.NumberFormat("en-US", { style: "currency", currency, maximumFractionDigits: 0 }).format(value); }
export function dateTime(value?: string, locale = "en") { return value ? new Intl.DateTimeFormat(locale, { dateStyle: "medium", timeStyle: "short" }).format(new Date(value)) : "—"; }
