import express from "express";
import Stripe from "stripe";
import {agentIdSchema,assertJourneyTransition,assignJobSchema,journeyStageSchema,localeSchema,stageOwner} from "@pageloom/core";
import {z} from "zod";
import {authenticate,requireCeo,requireRole,type AuthenticatedRequest} from "./auth.js";
import {secrets} from "./config.js";
import {db} from "./firebase.js";
import {ToolGateway} from "./tool-gateway.js";

export const app=express();app.disable("x-powered-by");app.use((_req,res,next)=>{res.setHeader("Cache-Control","no-store");res.setHeader("X-Content-Type-Options","nosniff");next()});
app.post("/api/webhooks/stripe",express.raw({type:"application/json"}),async(req,res)=>{try{const stripe=new Stripe(secrets.stripe.value());const event=stripe.webhooks.constructEvent(req.body,req.headers["stripe-signature"] as string,secrets.stripeWebhook.value());await db.doc(`webhookEvents/stripe_${event.id}`).create({provider:"stripe",type:event.type,createdAt:new Date().toISOString(),data:event.data.object});res.json({received:true})}catch(error){res.status(400).json({error:{code:"INVALID_WEBHOOK",message:error instanceof Error?error.message:"Invalid webhook"}})}});
app.use(express.json({limit:"2mb"}));app.use("/api",authenticate);

app.get("/api/me",async(req:AuthenticatedRequest,res)=>{const memberships=await db.collectionGroup("members").where("uid","==",req.user!.uid).limit(20).get();res.json({data:{user:req.user,organizations:memberships.docs.map(doc=>({id:doc.ref.parent.parent!.id,...doc.data()}))}})});

app.post("/api/jobs",async(req:AuthenticatedRequest,res)=>{try{const input=assignJobSchema.parse(req.body);if(await requireRole(req,res,input.organizationId)===undefined)return;if(input.projectId){const project=await db.doc(`organizations/${input.organizationId}/projects/${input.projectId}`).get();if(!project.exists||!project.data()?.dealClosedAt)return res.status(409).json({error:{code:"DEAL_NOT_CLOSED",message:"Project AI work cannot start before the CEO records a closed deal"}})}const ref=db.collection(`organizations/${input.organizationId}/tasks`).doc();const now=new Date().toISOString();await ref.set({id:ref.id,...input,status:"queued",createdBy:req.user!.uid,createdAt:now,updatedAt:now,attempt:0});await activity(input.organizationId,"task.assigned",{taskId:ref.id,agentId:input.agentId,createdBy:req.user!.uid});return res.status(202).json({data:{id:ref.id}})}catch(error){return handle(error,res)}});

app.post("/api/projects",async(req:AuthenticatedRequest,res)=>{try{const input=z.object({organizationId:z.string(),leadId:z.string().min(1),name:z.string().min(2),clientName:z.string().min(2),locale:localeSchema.default("en"),budget:z.number().nonnegative().default(0),dealEvidence:z.string().min(10).max(2000),deadline:z.string().datetime().optional()}).parse(req.body);if(await requireCeo(req,res,input.organizationId)===undefined)return;const ref=db.collection(`organizations/${input.organizationId}/projects`).doc();const task=db.collection(`organizations/${input.organizationId}/tasks`).doc();const event=db.collection(`organizations/${input.organizationId}/journeyEvents`).doc();const now=new Date().toISOString();const batch=db.batch();batch.set(ref,{id:ref.id,...input,status:"planning",journeyStage:"deal_closed",progress:10,revenue:0,cost:0,dealClosedAt:now,dealClosedBy:req.user!.uid,createdAt:now,updatedAt:now});batch.set(task,{id:task.id,organizationId:input.organizationId,projectId:ref.id,agentId:"client-journey",objective:"Prepare the post-close questionnaire and asset collection plan. Do not contact the customer; submit outbound communication for CEO approval.",locale:input.locale,priority:"high",status:"queued",context:{journeyStage:"deal_closed",leadId:input.leadId,depth:0},constraints:["Deal closure is human-recorded","Customer never interacts with AI","Outbound communication requires CEO approval"],createdBy:"deal-close-workflow",createdAt:now,updatedAt:now,attempt:0});batch.set(event,{id:event.id,projectId:ref.id,from:"ceo_call",to:"deal_closed",actorType:"human",actorId:req.user!.uid,evidence:input.dealEvidence,createdAt:now});await batch.commit();await activity(input.organizationId,"deal.closed",{projectId:ref.id,leadId:input.leadId,closedBy:req.user!.uid});return res.status(201).json({data:{id:ref.id,taskId:task.id}})}catch(error){return handle(error,res)}});

app.post("/api/projects/:projectId/journey",async(req:AuthenticatedRequest,res)=>{try{const input=z.object({organizationId:z.string(),nextStage:journeyStageSchema,evidence:z.string().min(3).max(5000)}).parse(req.body);if(await requireCeo(req,res,input.organizationId)===undefined)return;const projectId=String(req.params.projectId);const ref=db.doc(`organizations/${input.organizationId}/projects/${projectId}`);const snap=await ref.get();if(!snap.exists)return res.status(404).json({error:{code:"NOT_FOUND",message:"Project not found"}});const current=journeyStageSchema.parse(snap.data()!.journeyStage);assertJourneyTransition(current,input.nextStage);const now=new Date().toISOString();const batch=db.batch();batch.update(ref,{journeyStage:input.nextStage,progress:journeyProgress(input.nextStage),updatedAt:now,...(input.nextStage==="customer_approval"?{customerApprovedAt:now}:{}),...(input.nextStage==="deployment"?{status:"review"}:{}),...(input.nextStage==="support"?{deployedAt:now,status:"active"}:{}),...(input.nextStage==="maintenance"?{status:"completed"}:{})});const event=db.collection(`organizations/${input.organizationId}/journeyEvents`).doc();batch.set(event,{id:event.id,projectId,from:current,to:input.nextStage,actorType:"human",actorId:req.user!.uid,evidence:input.evidence,createdAt:now});const owner=stageOwner[input.nextStage];if(owner!=="ceo"){const task=db.collection(`organizations/${input.organizationId}/tasks`).doc();batch.set(task,{id:task.id,organizationId:input.organizationId,projectId,agentId:owner,objective:`Execute the ${input.nextStage.replaceAll("_"," ")} stage for this verified post-close project.`,locale:snap.data()!.locale??"en",priority:"high",status:"queued",context:{journeyStage:input.nextStage,depth:0},constraints:["Customer never interacts with AI","Protected actions require CEO approval"],createdBy:"customer-journey",createdAt:now,updatedAt:now,attempt:0})}await batch.commit();await activity(input.organizationId,"journey.advanced",{projectId,from:current,to:input.nextStage});return res.json({data:{projectId,stage:input.nextStage}})}catch(error){return handle(error,res)}});

app.post("/api/chats/:chatId/messages",async(req:AuthenticatedRequest,res)=>{try{const input=z.object({organizationId:z.string(),agentId:agentIdSchema,content:z.string().min(1).max(20_000),locale:localeSchema.default("en")}).parse(req.body);if(await requireRole(req,res,input.organizationId,["owner","admin","operator","member"])===undefined)return;const chatId=String(req.params.chatId);const message=db.collection(`organizations/${input.organizationId}/chats/${chatId}/messages`).doc();const task=db.collection(`organizations/${input.organizationId}/tasks`).doc();const now=new Date().toISOString();const batch=db.batch();batch.set(message,{id:message.id,organizationId:input.organizationId,chatId,agentId:input.agentId,role:"user",content:input.content,locale:input.locale,createdBy:req.user!.uid,createdAt:now});batch.set(task,{id:task.id,organizationId:input.organizationId,agentId:input.agentId,objective:`Respond internally to the CEO dashboard message: ${input.content}`,locale:input.locale,priority:"normal",status:"queued",context:{chatId,internalOnly:true},constraints:["Never contact a customer"],createdBy:req.user!.uid,createdAt:now,updatedAt:now,attempt:0});await batch.commit();return res.status(202).json({data:{messageId:message.id,taskId:task.id}})}catch(error){return handle(error,res)}});

app.post("/api/approvals/:approvalId/decision",async(req:AuthenticatedRequest,res)=>{try{const input=z.object({organizationId:z.string(),decision:z.enum(["approved","rejected"])}).parse(req.body);if(await requireCeo(req,res,input.organizationId)===undefined)return;const approvalId=String(req.params.approvalId);const ref=db.doc(`organizations/${input.organizationId}/approvals/${approvalId}`);const approval=await ref.get();if(!approval.exists||approval.data()?.status!=="pending")return res.status(409).json({error:{code:"INVALID_STATE",message:"Approval is no longer pending"}});await ref.update({status:input.decision,decidedBy:req.user!.uid,decidedAt:new Date().toISOString(),authority:"ceo"});if(input.decision==="approved"){const value=approval.data()!;try{const result=await new ToolGateway().execute({organizationId:input.organizationId,taskId:value.taskId,agentId:value.requestedBy,approvalId,request:{tool:value.tool,operation:value.operation,parameters:value.parameters,reason:value.reason,requiresApproval:true,idempotencyKey:value.idempotencyKey}});await ref.update({status:"executed",executionResult:result,executedAt:new Date().toISOString()})}catch(error){await ref.update({status:"failed",executionError:error instanceof Error?error.message:"Execution failed"});throw error}}return res.json({data:{id:ref.id,status:input.decision}})}catch(error){return handle(error,res)}});

app.get("/api/dashboard/:organizationId",async(req:AuthenticatedRequest,res)=>{const orgId=String(req.params.organizationId);if(await requireRole(req,res,orgId,["owner","admin","operator","member"])===undefined)return;const[tasks,approvals,projects,usage,revenue,analytics,communications,deployments,builds,crm]=await Promise.all([db.collection(`organizations/${orgId}/tasks`).get(),db.collection(`organizations/${orgId}/approvals`).where("status","==","pending").get(),db.collection(`organizations/${orgId}/projects`).get(),db.collection(`organizations/${orgId}/usage`).get(),db.collection(`organizations/${orgId}/revenue`).get(),db.doc(`organizations/${orgId}/metrics/current`).get(),db.collection(`organizations/${orgId}/communicationDrafts`).limit(100).get(),db.collection(`organizations/${orgId}/deployments`).limit(100).get(),db.collection(`organizations/${orgId}/builds`).limit(100).get(),db.doc(`organizations/${orgId}/crm/summary`).get()]);const taskData=tasks.docs.map(doc=>doc.data());const projectData=projects.docs.map(doc=>doc.data());const usageData=usage.docs.map(doc=>doc.data());const revenueTotal=revenue.docs.reduce((sum,doc)=>sum+Number(doc.data().amount??0),0);const costs=projectData.reduce((sum,project)=>sum+Number(project.cost??0),0);return res.json({data:{activeAgents:new Set(taskData.filter(task=>task.status==="running").map(task=>task.agentId)).size,queuedTasks:taskData.filter(task=>task.status==="queued").length,pendingApprovals:approvals.size,activeProjects:projectData.filter(project=>["planning","active","review"].includes(project.status)).length,revenue:revenueTotal,costs,grossProfit:revenueTotal-costs,aiCostUsd:usageData.reduce((sum,item)=>sum+Number(item.estimatedCostUsd??0),0),apiCalls:usage.size,tokenUsage:usageData.reduce((sum,item)=>sum+Number(item.inputTokens??0)+Number(item.outputTokens??0),0),analytics:analytics.data()?.analytics??{sessions:0,conversions:0,organicClicks:0},communications:{drafts:communications.size},deployments:{total:deployments.size,activeBuilds:builds.docs.filter(doc=>["queued","working"].includes(doc.data().status)).length},crm:crm.data()??{leads:0,openDeals:0,customers:0}}})});
app.use((_req,res)=>res.status(404).json({error:{code:"NOT_FOUND",message:"Route not found"}}));
function handle(error:unknown,res:express.Response){if(error instanceof z.ZodError)return res.status(422).json({error:{code:"VALIDATION_ERROR",message:"Request validation failed",issues:error.issues}});if(error instanceof Error&&error.message.startsWith("Invalid customer journey transition"))return res.status(409).json({error:{code:"INVALID_JOURNEY_TRANSITION",message:error.message}});console.error(error);return res.status(500).json({error:{code:"INTERNAL_ERROR",message:"The operation failed"}})}
async function activity(orgId:string,type:string,payload:unknown){const ref=db.collection(`organizations/${orgId}/activity`).doc();await ref.set({id:ref.id,type,payload,createdAt:new Date().toISOString()})}
function journeyProgress(stage:z.infer<typeof journeyStageSchema>){return({lead:0,ceo_call:5,deal_closed:10,questionnaire:18,assets:26,planning:35,ui_design:45,development:62,quality_assurance:75,customer_approval:84,deployment:92,support:97,maintenance:100}as const)[stage]}
