import type{NextFunction,Request,Response}from"express";import{auth,db}from"./firebase.js";
export interface AuthenticatedRequest extends Request{user?:{uid:string;email?:string;emailVerified:boolean;platformRole?:string}}
export async function authenticate(req:AuthenticatedRequest,res:Response,next:NextFunction){try{const header=req.headers.authorization;if(!header?.startsWith("Bearer "))return res.status(401).json({error:{code:"UNAUTHENTICATED",message:"Firebase ID token required"}});const token=await auth.verifyIdToken(header.slice(7),true);req.user={uid:token.uid,emailVerified:token.email_verified===true,...(token.email?{email:token.email}:{}),...(typeof token.platformRole==="string"?{platformRole:token.platformRole}:{})};next()}catch{return res.status(401).json({error:{code:"UNAUTHENTICATED",message:"Invalid or revoked Firebase ID token"}})}}
export async function requireRole(req:AuthenticatedRequest,res:Response,organizationId:string,roles:string[]=["owner","admin","operator"]){const member=await db.doc(`organizations/${organizationId}/members/${req.user!.uid}`).get();if(!member.exists||member.data()?.disabled===true||!roles.includes(String(member.data()?.role))){res.status(403).json({error:{code:"FORBIDDEN",message:"Organization role does not permit this action"}});return undefined}return member.data()!;}
export async function requireCeo(req:AuthenticatedRequest,res:Response,organizationId:string){return requireRole(req,res,organizationId,["owner"]);}
export async function platformAdministrator(req:AuthenticatedRequest){if(["owner","admin"].includes(req.user?.platformRole??""))return{role:req.user!.platformRole!,source:"claim"};const administrator=await db.doc(`systemAdministrators/${req.user!.uid}`).get();if(administrator.exists&&administrator.data()?.active!==false&&["owner","admin"].includes(String(administrator.data()?.role)))return{...administrator.data(),role:String(administrator.data()?.role),source:"registry"};return undefined;}
export async function requirePlatformAdmin(req:AuthenticatedRequest,res:Response){const administrator=await platformAdministrator(req);if(administrator)return administrator;res.status(403).json({error:{code:"PLATFORM_ADMIN_REQUIRED",message:"Platform administrator access is required"}});return undefined;}
export async function requirePlatformOrRole(req:AuthenticatedRequest,res:Response,organizationId:string,roles:string[]=["owner","admin"]){const administrator=await platformAdministrator(req);return administrator??requireRole(req,res,organizationId,roles);}
export async function requirePlatformProjectAccess(req:AuthenticatedRequest,res:Response,organizationId:string,projectId:string){const administrator=await platformAdministrator(req);return administrator??requireProjectAccess(req,res,organizationId,projectId);}
export async function requireProjectAccess(req:AuthenticatedRequest,res:Response,organizationId:string,projectId:string,roles:string[]=["owner","admin","operator","member","client"]){const member=await requireRole(req,res,organizationId,roles);if(member===undefined)return undefined;if(member.role!=="client")return member;const project=await db.doc(`organizations/${organizationId}/projects/${projectId}`).get(),allowedProjects=Array.isArray(member.projectIds)&&member.projectIds.length>0?member.projectIds.map(String):undefined;if(!project.exists||!member.customerId||project.data()?.customerId!==member.customerId||(allowedProjects&&!allowedProjects.includes(projectId))){res.status(403).json({error:{code:"FORBIDDEN",message:"Client access is limited to assigned customer projects"}});return undefined}return member;}
export function customerPermission(member:FirebaseFirestore.DocumentData,key:"contentEdit"|"support"|"comments"|"assets"){return member.role!=="client"||member.permissions?.[key]!==false;}
