import{readFileSync}from"node:fs";import{describe,expect,it}from"vitest";const rules=readFileSync(new URL("../../firestore.rules",import.meta.url),"utf8");describe("Firestore enterprise isolation",()=>{it("keeps all client writes server-authorized",()=>expect(rules).not.toContain("allow write: if client"));it("limits customer document reads by project and audience while signatures remain staff-only",()=>{expect(rules).toContain("clientProject(orgId, projectId) && resource.data.audience == 'customer'");expect(rules).toContain("documents/{documentId}/signatures/{signatureId} { allow read: if staff(orgId)")});it("limits client support reads to their customer account",()=>expect(rules).toContain("client(orgId) && resource.data.customerId == clientCustomerId(orgId)"));it("retains recursive default deny",()=>expect(rules).toContain("match /{document=**} { allow read, write: if false; }"))});
describe("Firestore role least-privilege",()=>{
  const privilegedOnly=["revenue","expenses","agentSettings","infrastructurePlans","backupRuns","domains","certificates","fleetResources","incidents","alerts","securityEvents","deadLetters","executions","apiKeys","secrets","auditLogs","scheduledJobs","maintenanceRequests","reviews","pricingPackages","legalDocuments"];
  it("defines a privileged() role tier excluding 'member'",()=>{expect(rules).toContain("function privileged(orgId)");expect(rules).toMatch(/function privileged\(orgId\) \{ return member\(orgId\) && role\(orgId\) in \['owner','admin','operator'\]/)});
  for(const collection of privilegedOnly){it(`restricts /${collection} to privileged() and not the broad staff() wildcard`,()=>{expect(rules).toContain(`match /${collection}/{docId} { allow read: if privileged(orgId); allow write: if false; }`);expect(rules).not.toMatch(new RegExp(`match /${collection}/\\{docId\\} \\{ allow read: if staff\\(orgId\\)`))})}
  it("does not use a generic wildcard collection match that would OR-override the privileged tier",()=>expect(rules).not.toContain("match /{collection}/{docId}"));
  it("restricts draft/undecided legal acceptances to privileged staff",()=>expect(rules).toContain("match /projects/{projectId}/legalAcceptances/{acceptanceId} { allow read: if privileged(orgId); allow write: if false; }"));
});
describe("website content isolation",()=>{it("allows customers to read only content bearing their own customer id while all writes remain server-authorized",()=>{expect(rules).toContain("match /websites/{websiteId}/content/{contentId}");expect(rules).toContain("resource.data.customerId == clientCustomerId(orgId)");expect(rules).not.toContain("content/{contentId} { allow write")});it("keeps content revision history privileged",()=>expect(rules).toContain("contentRevisions/{revisionId} { allow read: if privileged(orgId); allow write: if false; }"))});
describe("customer access lifecycle",()=>{it("denies disabled members and honors optional project assignments",()=>{expect(rules).toContain("data.disabled != true");expect(rules).toContain("'projectIds' in get(");expect(rules).toContain("projectId in get(")})});
