import {onRequest} from "firebase-functions/v2/https";
import {onDocumentCreated,onDocumentUpdated} from "firebase-functions/v2/firestore";
import {onSchedule} from "firebase-functions/v2/scheduler";
import {automatedStages,journeyStageSchema,nextJourneyStage,stageOwner,type JourneyStage,type Task} from "@pageloom/core";
import {app} from "./api.js";import {params,runtimeSecrets} from "./config.js";import {db} from "./firebase.js";import {CentralOrchestrator} from "./orchestrator.js";

export const api=onRequest({region:params.region,secrets:runtimeSecrets,timeoutSeconds:120,memory:"1GiB",maxInstances:100,concurrency:40,invoker:"public"},app);
export const executeAgentTask=onDocumentCreated({document:"organizations/{organizationId}/tasks/{taskId}",region:params.region,secrets:runtimeSecrets,retry:true,timeoutSeconds:540,memory:"2GiB",maxInstances:50,concurrency:4},async event=>{if(event.data)await new CentralOrchestrator().run(event.params.organizationId,event.params.taskId)});
export const advanceCustomerJourney=onDocumentUpdated({document:"organizations/{organizationId}/tasks/{taskId}",region:params.region,retry:true},async event=>{const before=event.data?.before.data();const after=event.data?.after.data()as Task|undefined;if(!after||before?.status==="completed"||after.status!=="completed"||!after.projectId)return;const completed=journeyStageSchema.safeParse(after.context.journeyStage);if(!completed.success)return;const next=nextJourneyStage(completed.data);if(!next)return;const orgId=event.params.organizationId;const projectRef=db.doc(`organizations/${orgId}/projects/${after.projectId}`);const nextTaskRef=db.collection(`organizations/${orgId}/tasks`).doc();const journeyEventRef=db.collection(`organizations/${orgId}/journeyEvents`).doc();await db.runTransaction(async tx=>{const project=await tx.get(projectRef);if(!project.exists||project.data()?.journeyStage!==completed.data)return;const now=new Date().toISOString();tx.update(projectRef,{journeyStage:next,progress:journeyProgress(next),updatedAt:now,...(next==="customer_approval"?{status:"review"}:{})});tx.create(journeyEventRef,{id:journeyEventRef.id,projectId:after.projectId,from:completed.data,to:next,actorType:"orchestrator",sourceTaskId:after.id,createdAt:now});if(automatedStages.has(next)){const owner=stageOwner[next];tx.create(nextTaskRef,{id:nextTaskRef.id,organizationId:orgId,projectId:after.projectId,agentId:owner,objective:`Execute the ${next.replaceAll("_"," ")} stage using verified project context and artifacts.`,locale:after.locale,priority:"high",status:"queued",context:{journeyStage:next,depth:0,previousTaskId:after.id},constraints:["Customer never interacts directly with AI","All protected actions require CEO approval"],createdBy:"customer-journey",createdAt:now,updatedAt:now,attempt:0})}})});
export const dailyCeoReport=onSchedule({schedule:"0 8 * * *",timeZone:params.agencyTimezone,region:params.region,retryCount:3},async()=>{const orgs=await db.collection("organizations").where("autonomyEnabled","==",true).get();for(const org of orgs.docs){const key=new Date().toLocaleDateString("en-CA",{timeZone:params.agencyTimezone.value()});const ref=db.doc(`organizations/${org.id}/scheduledJobs/ceo-daily-${key}`);try{await ref.create({createdAt:new Date().toISOString()})}catch{continue}const task=db.collection(`organizations/${org.id}/tasks`).doc();await task.set({id:task.id,organizationId:org.id,agentId:"ceo",objective:"Produce today's executive report from verified operating data. Analyze priorities, projects, pipeline, analytics, revenue, cost, API usage, and agent performance; delegate urgent internal outcomes.",locale:org.data().defaultLocale??"en",priority:"high",status:"queued",context:{schedule:"daily-ceo",date:key,internalOnly:true},constraints:["Use only verified data","Never contact customers","Protected actions require CEO approval"],createdBy:"scheduler",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),attempt:0})}});
function journeyProgress(stage:JourneyStage){return({lead:0,ceo_call:5,deal_closed:10,questionnaire:18,assets:26,planning:35,ui_design:45,development:62,quality_assurance:75,customer_approval:84,deployment:92,support:97,maintenance:100}as const)[stage]}
