import {createHash} from "node:crypto";
import {buildPrompt,createQuestionnaireSchema,evaluateAiBudget,getAgent,routeModel,workflowDeliverables,workflowStageSchema,type ActionRequest,type AgentOutput,type Task} from "@pageloom/core";
import type {DocumentReference} from "firebase-admin/firestore";
import {db,storage} from "./firebase.js";
import {executeModel} from "./model-providers.js";
import {recordUsage} from "./cost.js";
import {getToolPolicy} from "./tool-policy.js";
import {ToolGateway} from "./tool-gateway.js";

const gateway=new ToolGateway();
export class CentralOrchestrator {
  async run(organizationId:string,taskId:string){
    const ref=db.doc(`organizations/${organizationId}/tasks/${taskId}`);const scheduled=await ref.get(),notBefore=scheduled.data()?.notBefore;if(typeof notBefore==="string"&&Date.parse(notBefore)>Date.now())throw new Error(`Task is scheduled for ${notBefore}`);const task=await this.claim(ref);if(!task)return;
    const agentSettings=await db.doc(`organizations/${organizationId}/agentSettings/${task.agentId}`).get();if(agentSettings.data()?.paused===true){await ref.update({status:"cancelled",error:"Agent is paused by the CEO",completedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});return}
    let verifiedContext:Record<string,unknown>={};if(task.projectId){const project=await db.doc(`organizations/${organizationId}/projects/${task.projectId}`).get();if(!project.exists||!project.data()?.dealClosedAt){await ref.update({status:"failed",error:"AI project work is blocked until the CEO records a closed deal",completedAt:new Date().toISOString()});return}const projectData=project.data()!,questionnaireId=typeof projectData.questionnaireId==="string"?projectData.questionnaireId:undefined;const[questionnaire,priorTasks]=await Promise.all([questionnaireId?db.doc(`organizations/${organizationId}/projects/${task.projectId}/questionnaires/${questionnaireId}`).get():Promise.resolve(undefined),db.collection(`organizations/${organizationId}/tasks`).where("projectId","==",task.projectId).limit(100).get()]);verifiedContext={project:{...projectData,id:project.id},questionnaire:questionnaire?.data()??projectData.questionnaire??null,priorStageOutputs:priorTasks.docs.map(doc=>doc.data()as Task).filter(item=>item.id!==task.id&&item.status==="completed"&&item.output).slice(-20).map(item=>({agentId:item.agentId,stage:item.context.workflowStage,summary:item.output!.summary,deliverables:item.output!.deliverables.map(deliverable=>({type:deliverable.type,title:deliverable.title,content:deliverable.content.slice(0,12000)})),evidence:item.output!.workflowOutcome.evidence}))}}
    const agent=getAgent(task.agentId),org=(await db.doc(`organizations/${organizationId}`).get()).data()??{},requiresCode=["website-architect","frontend-builder","backend","firebase","qa","deployment"].includes(task.agentId),[usage,running]=await Promise.all([db.collection(`organizations/${organizationId}/usage`).get(),db.collection(`organizations/${organizationId}/tasks`).where("status","==","running").get()]),spent=usage.docs.reduce((sum,item)=>sum+Number(item.data().estimatedCostUsd??0),0),reserved=running.docs.filter(item=>item.id!==taskId).reduce((sum,item)=>sum+Number(item.data().reservedCostUsd??4),0),budget=evaluateAiBudget(Number(org.aiBudgetUsd??org.aiBudgetRemainingUsd??100),spent,reserved,4);if(!budget.allowed){await ref.update({status:"awaiting_approval",error:budget.reason,approvalReason:"ai_budget",updatedAt:new Date().toISOString()});await this.activity(organizationId,"task.budget_blocked",task,{remainingUsd:budget.remainingUsd});return}await ref.update({reservedCostUsd:4,budgetRemainingAtStartUsd:budget.remainingUsd});
    const route=routeModel({agent,priority:task.priority,requiresCode,requiresGoogleContext:task.context.googleContext===true,budgetRemainingUsd:budget.remainingUsd,providerHealth:{openai:true,gemini:true}}),workflowStage=workflowStageSchema.safeParse(task.context.workflowStage),requiredDeliverables=workflowStage.success?workflowDeliverables[workflowStage.data]??[]:[];const prompt=buildPrompt(agent,{objective:task.objective,locale:task.locale,context:{...task.context,...verifiedContext,requiredDeliverables},constraints:[...task.constraints,...(requiredDeliverables.length?[`Return every required deliverable type exactly: ${requiredDeliverables.join(", ")}`]:[])]});
    try{let execution;try{execution=await executeModel(route,agent,prompt,safetyId(organizationId))}catch(primaryError){const primaryProvider=route.provider;const fallback=routeModel({agent,priority:task.priority,requiresCode,requiresGoogleContext:false,budgetRemainingUsd:budget.remainingUsd,providerHealth:{openai:true,gemini:false}});execution=await executeModel(fallback,agent,prompt,safetyId(organizationId));Object.assign(route,fallback);await this.activity(organizationId,"model.fallback",task,{from:primaryProvider,to:fallback.provider,error:primaryError instanceof Error?primaryError.message:"provider failure"})}
      const cost=await recordUsage({organizationId,taskId,agentId:task.agentId,provider:route.provider,model:route.model,inputTokens:execution.inputTokens,outputTokens:execution.outputTokens,latencyMs:execution.latencyMs,...(execution.providerResponseId?{responseId:execution.providerResponseId}:{})}),delivered=new Set(execution.output.deliverables.map(item=>item.type)),missingDeliverables=requiredDeliverables.filter(type=>!delivered.has(type));await this.persistArtifacts(organizationId,taskId,execution.output);if(task.projectId&&task.context.workflowStage==="onboarding"&&execution.output.workflowOutcome.status==="passed"&&!missingDeliverables.length)await this.persistQuestionnaire(task,execution.output);const approvals=await this.processActions(task,execution.output.actionRequests);if(!task.projectId)await this.delegate(task,execution.output);const declaredFailure=execution.output.workflowOutcome.status==="failed"&&task.context.workflowStage!=="qa",workflowFailure=task.createdBy==="workflow-engine"&&(declaredFailure||missingDeliverables.length>0),failureReason=missingDeliverables.length?`Missing required deliverables: ${missingDeliverables.join(", ")}`:execution.output.workflowOutcome.reason;await ref.update({status:workflowFailure?"failed":approvals?"awaiting_approval":"completed",output:execution.output,...(workflowFailure?{error:failureReason}:{}),provider:route.provider,model:route.model,estimatedCostUsd:cost,completedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});if(typeof task.context.chatId==="string")await this.agentChatReply(task,execution.output);await this.activity(organizationId,workflowFailure?"task.failed":approvals?"task.awaiting_approval":"task.completed",task,{provider:route.provider,model:route.model,cost,workflowOutcome:execution.output.workflowOutcome.status,missingDeliverables})
    }catch(error){await ref.update({status:"failed",error:error instanceof Error?error.message:"Unknown execution error",updatedAt:new Date().toISOString(),completedAt:new Date().toISOString()});await this.activity(organizationId,"task.failed",task,{error:error instanceof Error?error.message:"Unknown execution error"});throw error}
  }
  private async claim(ref:DocumentReference){return db.runTransaction(async tx=>{const snap=await tx.get(ref);if(!snap.exists||snap.data()?.status!=="queued")return undefined;const task={id:snap.id,...snap.data()}as Task;tx.update(ref,{status:"running",attempt:(task.attempt??0)+1,startedAt:new Date().toISOString(),updatedAt:new Date().toISOString()});return task})}
  private async processActions(task:Task,requests:ActionRequest[]){let pending=0;for(const request of requests.slice(0,20)){const policy=getToolPolicy(request.tool,request.operation,task.agentId);const approvalRequired=policy.approval==="always"||policy.approval==="writes"&&policy.sideEffect;if(approvalRequired){const ref=db.collection(`organizations/${task.organizationId}/approvals`).doc();await ref.set({id:ref.id,organizationId:task.organizationId,taskId:task.id,tool:request.tool,operation:request.operation,parameters:request.parameters,reason:request.reason,status:"pending",authority:"ceo",requestedBy:task.agentId,requestedAt:new Date().toISOString(),idempotencyKey:request.idempotencyKey});pending++}else await gateway.execute({organizationId:task.organizationId,taskId:task.id,agentId:task.agentId,request:{...request,requiresApproval:false}})}return pending>0}
  private async delegate(task:Task,output:AgentOutput){const depth=Number(task.context.depth??0);if(depth>=4)return;for(const delegated of output.delegatedTasks.slice(0,12)){if(delegated.agentId===task.agentId&&delegated.objective===task.objective)continue;const ref=db.collection(`organizations/${task.organizationId}/tasks`).doc();await ref.set({id:ref.id,organizationId:task.organizationId,...(task.projectId?{projectId:task.projectId}:{}),agentId:delegated.agentId,objective:delegated.objective,locale:task.locale,priority:delegated.priority,status:"queued",context:{...delegated.context,depth:depth+1,parentTaskId:task.id},constraints:[...task.constraints,"Customer never interacts directly with AI","Protected actions require CEO approval"],createdBy:"central-orchestrator",createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),attempt:0})}}
  private async persistArtifacts(orgId:string,taskId:string,output:AgentOutput){for(const deliverable of output.deliverables)for(const file of deliverable.files.slice(0,100)){const path=file.path.replace(/\.\./g,"").replace(/^\/+/,"").replace(/[^a-zA-Z0-9._\-/]/g,"-");if(path)await storage.bucket().file(`organizations/${orgId}/artifacts/${taskId}/${path}`).save(file.content,{resumable:false,contentType:contentType(path),metadata:{metadata:{taskId},cacheControl:"private,max-age=3600"}})}}
  private async persistQuestionnaire(task:Task,output:AgentOutput){const deliverable=output.deliverables.find(item=>item.type==="questionnaire_schema");if(!deliverable||!task.projectId)throw new Error("Onboarding did not return a questionnaire schema");const parsed=createQuestionnaireSchema.parse({organizationId:task.organizationId,...JSON.parse(deliverable.content)}),collection=db.collection(`organizations/${task.organizationId}/projects/${task.projectId}/questionnaires`),versions=await collection.orderBy("version","desc").limit(1).get(),version=Number(versions.docs[0]?.data().version??0)+1,ref=collection.doc(`workflow-${task.id}`),now=new Date().toISOString();await ref.set({id:ref.id,projectId:task.projectId,...parsed,version,status:"draft",responses:{},filePaths:[],createdAt:now,updatedAt:now,createdBy:task.agentId});await db.doc(`organizations/${task.organizationId}/projects/${task.projectId}`).update({questionnaireId:ref.id,questionnaireVersion:version,journeyStage:"questionnaire",websiteStatus:"questionnaire",aiExecutionStatus:"waiting_for_customer",updatedAt:now})}
  private async agentChatReply(task:Task,output:AgentOutput){const chatId=String(task.context.chatId);const ref=db.collection(`organizations/${task.organizationId}/chats/${chatId}/messages`).doc();await ref.set({id:ref.id,organizationId:task.organizationId,chatId,agentId:task.agentId,role:"agent",content:output.message,locale:task.locale,createdBy:task.agentId,createdAt:new Date().toISOString(),taskId:task.id,internalOnly:true})}
  private async activity(orgId:string,type:string,task:Task,payload:Record<string,unknown>){const ref=db.collection(`organizations/${orgId}/activity`).doc();await ref.set({id:ref.id,type,taskId:task.id,agentId:task.agentId,payload,createdAt:new Date().toISOString()})}
}
const safetyId=(value:string)=>`org_${createHash("sha256").update(value).digest("hex").slice(0,32)}`;
const contentType=(path:string)=>path.endsWith(".json")?"application/json":path.endsWith(".tsx")||path.endsWith(".ts")?"text/plain; charset=utf-8":path.endsWith(".html")?"text/html; charset=utf-8":path.endsWith(".css")?"text/css; charset=utf-8":"text/plain; charset=utf-8";
