import{CloudBuildClient}from"@google-cloud/cloudbuild";import{google}from"googleapis";import Stripe from"stripe";import{z}from"zod";import type{ActionRequest,AgentId}from"@pageloom/core";import{params,secrets}from"./config.js";import{db,storage}from"./firebase.js";import{getToolPolicy}from"./tool-policy.js";
const base=z.object({});
// A CRM path must stay relative to CRM_BASE_URL. `new URL(path, base)` treats an absolute
// or protocol-relative path as its own origin, ignoring `base` entirely — an attacker-
// controlled `path` like "https://evil.example/" would send the CRM bearer token to an
// arbitrary host (SSRF + credential exfiltration). Reject anything that isn't a plain relative path.
export const relativePath=z.string().min(1).refine(value=>!/^([a-zA-Z][a-zA-Z0-9+.-]*:)?\/\//.test(value)&&!value.startsWith("\\"),"path must be relative, not an absolute or protocol-relative URL");
const schemas:Record<string,z.ZodTypeAny>={"gmail.draft":z.object({to:z.string().email(),subject:z.string(),body:z.string()}),"gmail.send":z.object({draftId:z.string()}),"calendar.create_event":z.object({summary:z.string(),start:z.string().datetime(),end:z.string().datetime(),attendees:z.array(z.string().email()).default([])}),"drive.create_document":z.object({name:z.string(),content:z.string().default("")}),"drive.create_sheet":z.object({title:z.string()}),"analytics.read":z.object({propertyId:z.string(),startDate:z.string(),endDate:z.string(),metrics:z.array(z.string()).min(1),dimensions:z.array(z.string()).default([])}),"search_console.read":z.object({siteUrl:z.string().url(),startDate:z.string(),endDate:z.string(),dimensions:z.array(z.string()).default(["query"])}),"business_profile.read":z.object({accountId:z.string()}),"tag_manager.read":z.object({accountId:z.string()}),"tag_manager.publish":z.object({containerPath:z.string(),versionId:z.string()}),"maps.geocode":z.object({address:z.string()}),"maps.places":z.object({query:z.string()}),"whatsapp.send":z.object({to:z.string(),message:z.string()}),"resend.send":z.object({to:z.string().email(),subject:z.string(),html:z.string()}),"twilio.send_sms":z.object({to:z.string(),body:z.string().max(1600)}),"crm.read":z.object({path:relativePath}),"crm.upsert":z.object({path:relativePath,data:z.record(z.unknown())}),"stripe.invoice_draft":z.object({customerId:z.string(),currency:z.string().length(3),items:z.array(z.object({description:z.string(),amountMinor:z.number().int().positive(),quantity:z.number().int().positive().default(1)}))}),"stripe.payment_link":z.object({priceId:z.string(),quantity:z.number().int().positive().default(1)}),"paypal.order_draft":z.object({currency:z.string().length(3),amount:z.string()}),"make.trigger":z.object({url:z.string().url(),payload:z.record(z.unknown())}),"n8n.execute":z.object({workflowId:z.string(),payload:z.record(z.unknown())}),"github.read":z.object({path:z.string().startsWith("/repos/")}),"github.create_release":z.object({owner:z.string(),repo:z.string(),tagName:z.string(),name:z.string(),body:z.string()}),"gcp.cloud_build":z.object({bucket:z.string(),object:z.string(),substitutions:z.record(z.string()).default({})}),"gcp.cloud_run_deploy":z.object({service:z.string(),region:z.string(),image:z.string()}),"storage.write_artifact":z.object({path:z.string(),content:z.string(),contentType:z.string().default("text/plain")})};
export class ToolGateway{async execute(input:{organizationId:string;taskId:string;agentId:AgentId;request:ActionRequest;approvalId?:string}){const{request}=input;const policy=getToolPolicy(request.tool,request.operation,input.agentId);const key=`${request.tool}.${request.operation}`;const parameters=(schemas[key]??base.passthrough()).parse(request.parameters);if(policy.approval==="always"||policy.approval==="writes"&&policy.sideEffect){if(!input.approvalId)throw new Error(`Approval required for ${key}`);const approval=await db.doc(`organizations/${input.organizationId}/approvals/${input.approvalId}`).get();if(!approval.exists||approval.data()?.status!=="approved")throw new Error("A valid approved action is required");}const ref=db.doc(`organizations/${input.organizationId}/executions/${request.idempotencyKey}`);const claimed=await db.runTransaction(async(tx)=>{const current=await tx.get(ref);if(current.exists)return false;tx.create(ref,{tool:request.tool,operation:request.operation,taskId:input.taskId,agentId:input.agentId,status:"running",createdAt:new Date().toISOString()});return true});if(!claimed)return(await ref.get()).data()?.result;try{const result=await this.invoke(request.tool,request.operation,parameters,input.organizationId);await ref.update({status:"completed",result,completedAt:new Date().toISOString()});return result}catch(error){await ref.update({status:"failed",error:error instanceof Error?error.message:"Unknown integration failure",completedAt:new Date().toISOString()});throw error}}
private async invoke(tool:string,operation:string,p:any,orgId:string):Promise<unknown>{if(tool==="storage"){const object=`organizations/${orgId}/artifacts/${p.path.replace(/^\/+/,"")}`;await storage.bucket().file(object).save(p.content,{contentType:p.contentType,resumable:false,metadata:{cacheControl:"private,max-age=3600"}});return{object}}
if(tool==="firestore"){const input=z.object({path:z.string().startsWith(`organizations/${orgId}/`)}).parse(p);const snap=await db.doc(input.path).get();return snap.exists?{id:snap.id,...snap.data()}:null}
if(tool==="whatsapp"&&operation==="draft"){const input=z.object({to:z.string(),message:z.string()}).parse(p);const ref=db.collection(`organizations/${orgId}/communicationDrafts`).doc();await ref.set({id:ref.id,channel:"whatsapp",...input,status:"draft",createdAt:new Date().toISOString()});return{id:ref.id,status:"draft"}}
if(tool==="docs"||tool==="sheets"){const auth=workspaceAuth();if(tool==="docs"){const input=z.object({name:z.string(),content:z.string()}).parse(p);const file=await google.drive({version:"v3",auth}).files.create({requestBody:{name:input.name,mimeType:"application/vnd.google-apps.document"},fields:"id,webViewLink"});if(file.data.id)await google.docs({version:"v1",auth}).documents.batchUpdate({documentId:file.data.id,requestBody:{requests:[{insertText:{location:{index:1},text:input.content}}]}});return file.data}const common=z.object({spreadsheetId:z.string(),range:z.string()}).parse(p);const sheets=google.sheets({version:"v4",auth});if(operation==="read"){const result=await sheets.spreadsheets.values.get(common);return result.data}const values=z.array(z.array(z.union([z.string(),z.number(),z.boolean(),z.null()]))).parse(p.values);const result=operation==="append"?await sheets.spreadsheets.values.append({...common,valueInputOption:"USER_ENTERED",requestBody:{values}}):await sheets.spreadsheets.values.update({...common,valueInputOption:"USER_ENTERED",requestBody:{values}});return result.data}
if(tool==="gmail"||tool==="calendar"||tool==="drive"||tool==="analytics"||tool==="search_console"){const auth=workspaceAuth();if(tool==="gmail"){const api=google.gmail({version:"v1",auth});if(operation==="draft"){const raw=Buffer.from(`To: ${p.to}\r\nSubject: ${p.subject}\r\nContent-Type: text/plain; charset=utf-8\r\n\r\n${p.body}`).toString("base64url");const result=await api.users.drafts.create({userId:"me",requestBody:{message:{raw}}});return{id:result.data.id}}const result=await api.users.drafts.send({userId:"me",requestBody:{id:p.draftId}});return{id:result.data.id}}
if(tool==="calendar"){const result=await google.calendar({version:"v3",auth}).events.insert({calendarId:"primary",requestBody:{summary:p.summary,start:{dateTime:p.start},end:{dateTime:p.end},attendees:p.attendees.map((email:string)=>({email}))}});return{id:result.data.id,htmlLink:result.data.htmlLink}}
if(tool==="drive"){if(operation==="create_document"){const result=await google.drive({version:"v3",auth}).files.create({requestBody:{name:p.name,mimeType:"application/vnd.google-apps.document"},fields:"id,webViewLink"});if(p.content&&result.data.id)await google.docs({version:"v1",auth}).documents.batchUpdate({documentId:result.data.id,requestBody:{requests:[{insertText:{location:{index:1},text:p.content}}]}});return result.data}const result=await google.sheets({version:"v4",auth}).spreadsheets.create({requestBody:{properties:{title:p.title}}});return{spreadsheetId:result.data.spreadsheetId,spreadsheetUrl:result.data.spreadsheetUrl}}
if(tool==="analytics"){const result=await google.analyticsdata({version:"v1beta",auth}).properties.runReport({property:`properties/${p.propertyId}`,requestBody:{dateRanges:[{startDate:p.startDate,endDate:p.endDate}],metrics:p.metrics.map((name:string)=>({name})),dimensions:p.dimensions.map((name:string)=>({name}))}});return result.data}
const result=await google.searchconsole({version:"v1",auth}).searchanalytics.query({siteUrl:p.siteUrl,requestBody:{startDate:p.startDate,endDate:p.endDate,dimensions:p.dimensions}});return result.data}
if(tool==="business_profile"){const auth=workspaceAuth();const result=await google.mybusinessbusinessinformation({version:"v1",auth}).accounts.locations.list({parent:`accounts/${p.accountId}`,readMask:"name,title,storefrontAddress,phoneNumbers,websiteUri,metadata"});return result.data}
if(tool==="tag_manager"){const auth=workspaceAuth();const api=google.tagmanager({version:"v2",auth});if(operation==="read"){const result=await api.accounts.containers.list({parent:`accounts/${p.accountId}`});return result.data}const result=await api.accounts.containers.versions.publish({path:`${p.containerPath}/versions/${p.versionId}`});return result.data}
if(tool==="maps"){const url=new URL(operation==="places"?"https://maps.googleapis.com/maps/api/place/textsearch/json":"https://maps.googleapis.com/maps/api/geocode/json");url.searchParams.set(operation==="places"?"query":"address",operation==="places"?p.query:p.address);url.searchParams.set("key",secrets.maps.value());return checkedJson(await fetch(url))}
if(tool==="stripe"){const stripe=new Stripe(secrets.stripe.value());if(operation==="invoice_draft"){const invoice=await stripe.invoices.create({customer:p.customerId,currency:p.currency,auto_advance:false});if(!invoice.id)throw new Error("Stripe did not return an invoice ID");for(const item of p.items)await stripe.invoiceItems.create({customer:p.customerId,invoice:invoice.id,currency:p.currency,amount:item.amountMinor*item.quantity,description:item.description});return{id:invoice.id,status:invoice.status}}if(operation==="payment_link"){const link=await stripe.paymentLinks.create({line_items:[{price:p.priceId,quantity:p.quantity}]});return{id:link.id,url:link.url}}const input=z.object({paymentIntentId:z.string(),amountMinor:z.number().int().positive().optional()}).parse(p);const refund=await stripe.refunds.create({payment_intent:input.paymentIntentId,...(input.amountMinor?{amount:input.amountMinor}:{})});return{id:refund.id,status:refund.status}}
if(tool==="paypal"){const token=await paypalToken();if(operation==="refund"){const input=z.object({captureId:z.string(),currency:z.string().length(3).optional(),amount:z.string().optional()}).refine(value=>(value.currency&&value.amount)||(!value.currency&&!value.amount)).parse(p);return checkedJson(await fetch(`https://api-m.paypal.com/v2/payments/captures/${encodeURIComponent(input.captureId)}/refund`,{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json","paypal-request-id":crypto.randomUUID()},body:JSON.stringify(input.amount?{amount:{currency_code:input.currency,value:input.amount}}:{})}))}return checkedJson(await fetch("https://api-m.paypal.com/v2/checkout/orders",{method:"POST",headers:{authorization:`Bearer ${token}`,"content-type":"application/json","paypal-request-id":crypto.randomUUID()},body:JSON.stringify({intent:"CAPTURE",purchase_units:[{amount:{currency_code:p.currency,value:p.amount}}]})}))}
if(tool==="whatsapp"){return checkedJson(await fetch(`https://graph.facebook.com/v23.0/${secrets.whatsappPhone.value()}/messages`,{method:"POST",headers:{authorization:`Bearer ${secrets.whatsapp.value()}`,"content-type":"application/json"},body:JSON.stringify({messaging_product:"whatsapp",to:p.to,type:"text",text:{body:p.message}})}))}
if(tool==="resend"){const from=params.resendFrom.value();if(!from)throw new Error("RESEND_FROM_EMAIL is not configured");return checkedJson(await fetch("https://api.resend.com/emails",{method:"POST",headers:{authorization:`Bearer ${secrets.resend.value()}`,"content-type":"application/json","Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({from,to:[p.to],subject:p.subject,html:p.html})}))}
if(tool==="twilio"){const from=params.twilioFrom.value();if(!from)throw new Error("TWILIO_FROM_NUMBER is not configured");const body=new URLSearchParams({To:p.to,From:from,Body:p.body});const authorization=Buffer.from(`${secrets.twilioSid.value()}:${secrets.twilioToken.value()}`).toString("base64");return checkedJson(await fetch(`https://api.twilio.com/2010-04-01/Accounts/${secrets.twilioSid.value()}/Messages.json`,{method:"POST",headers:{authorization:`Basic ${authorization}`,"content-type":"application/x-www-form-urlencoded"},body}))}
if(tool==="crm"){const base=params.crmBaseUrl.value();if(!base)throw new Error("CRM_BASE_URL is not configured");return checkedJson(await fetch(new URL(p.path,base),{method:operation==="read"?"GET":"PUT",headers:{authorization:`Bearer ${secrets.crmToken.value()}`,"content-type":"application/json"},...(operation==="read"?{}:{body:JSON.stringify(p.data)})}))}
if(tool==="make"){return checkedJson(await fetch(p.url,{method:"POST",headers:{"content-type":"application/json","x-pageloom-signature":secrets.make.value()},body:JSON.stringify(p.payload)}))}
if(tool==="n8n"){const base=params.n8nBaseUrl.value();if(!base)throw new Error("N8N_BASE_URL is not configured");return checkedJson(await fetch(`${base.replace(/\/$/,"")}/api/v1/workflows/${encodeURIComponent(p.workflowId)}/run`,{method:"POST",headers:{"X-N8N-API-KEY":secrets.n8n.value(),"content-type":"application/json"},body:JSON.stringify(p.payload)}))}
if(tool==="github"){const url=operation==="read"?`https://api.github.com${p.path}`:`https://api.github.com/repos/${encodeURIComponent(p.owner)}/${encodeURIComponent(p.repo)}/releases`;return checkedJson(await fetch(url,{method:operation==="read"?"GET":"POST",headers:{authorization:`Bearer ${secrets.github.value()}`,accept:"application/vnd.github+json","x-github-api-version":"2022-11-28",...(operation==="read"?{}:{"content-type":"application/json"})},...(operation==="read"?{}:{body:JSON.stringify({tag_name:p.tagName,name:p.name,body:p.body,draft:true})})}))}
if(tool==="gcp"){const projectId=params.gcpDeployProject.value();if(!projectId)throw new Error("GCP_DEPLOY_PROJECT_ID is not configured");if(operation==="cloud_run_deploy"){const auth=await google.auth.getClient({scopes:["https://www.googleapis.com/auth/cloud-platform"]});const run=google.run({version:"v2",auth});const name=`projects/${projectId}/locations/${p.region}/services/${p.service}`;const result=await run.projects.locations.services.patch({name,updateMask:"template.containers",requestBody:{name,template:{containers:[{image:p.image}]}}});return{name:result.data.name,done:result.data.done??false}}const client=new CloudBuildClient();const[operationHandle]=await client.createBuild({projectId,build:{source:{storageSource:{bucket:p.bucket,object:p.object}},substitutions:p.substitutions,steps:[{name:"gcr.io/cloud-builders/npm",args:["ci"]},{name:"gcr.io/cloud-builders/npm",args:["run","build"]},{name:"gcr.io/$PROJECT_ID/firebase",args:["deploy","--only","hosting"]}]}});const[build]=await operationHandle.promise();return{id:build.id,status:build.status}}
throw new Error(`No connector for ${tool}.${operation}`)}}
function workspaceAuth(){const value=JSON.parse(secrets.googleWorkspace.value())as{client_email:string;private_key:string};return new google.auth.JWT({email:value.client_email,key:value.private_key,subject:secrets.googleSubject.value(),scopes:["https://www.googleapis.com/auth/gmail.modify","https://www.googleapis.com/auth/calendar","https://www.googleapis.com/auth/drive","https://www.googleapis.com/auth/documents","https://www.googleapis.com/auth/spreadsheets","https://www.googleapis.com/auth/analytics.readonly","https://www.googleapis.com/auth/webmasters.readonly","https://www.googleapis.com/auth/business.manage","https://www.googleapis.com/auth/tagmanager.readonly","https://www.googleapis.com/auth/tagmanager.publish"]})}
async function checkedJson(response:Response){const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(`Integration returned ${response.status}: ${JSON.stringify(data).slice(0,500)}`);return data}
async function paypalToken(){const encoded=Buffer.from(`${secrets.paypalId.value()}:${secrets.paypalSecret.value()}`).toString("base64");const response=await fetch("https://api-m.paypal.com/v1/oauth2/token",{method:"POST",headers:{authorization:`Basic ${encoded}`,"content-type":"application/x-www-form-urlencoded"},body:"grant_type=client_credentials"});const data=await checkedJson(response)as{access_token:string};return data.access_token}
