import type { AgentId } from "@pageloom/core";
export interface ToolPolicy { tool:string; operations:readonly string[]; agents:readonly AgentId[]; approval:"always"|"writes"|"never"; sideEffect:boolean }
const all: AgentId[] = ["ceo","sales","client-journey","project-manager","website-architect","ui-ux-designer","frontend-builder","backend","firebase","seo","content","brand","media","qa","deployment","maintenance","support","marketing","finance","analytics","automation","crm"];
export const toolPolicies: readonly ToolPolicy[] = [
{tool:"gmail",operations:["draft"],agents:["client-journey","support","marketing","content"],approval:"never",sideEffect:false},{tool:"gmail",operations:["send"],agents:["client-journey","support","marketing"],approval:"always",sideEffect:true},
{tool:"calendar",operations:["read"],agents:["sales","project-manager","client-journey"],approval:"never",sideEffect:false},{tool:"calendar",operations:["create_event","update_event"],agents:["sales","project-manager","client-journey"],approval:"always",sideEffect:true},
{tool:"drive",operations:["read"],agents:all,approval:"never",sideEffect:false},{tool:"drive",operations:["create_document","create_sheet","upload"],agents:all,approval:"writes",sideEffect:true},{tool:"docs",operations:["create"],agents:["client-journey","content","seo","brand","project-manager"],approval:"writes",sideEffect:true},{tool:"sheets",operations:["read"],agents:all,approval:"never",sideEffect:false},{tool:"sheets",operations:["write","append"],agents:all,approval:"writes",sideEffect:true},
{tool:"analytics",operations:["read"],agents:["ceo","analytics","seo","marketing","maintenance"],approval:"never",sideEffect:false},{tool:"search_console",operations:["read"],agents:["ceo","analytics","seo"],approval:"never",sideEffect:false},{tool:"business_profile",operations:["read"],agents:["seo","analytics","marketing"],approval:"never",sideEffect:false},{tool:"tag_manager",operations:["read"],agents:["analytics","qa"],approval:"never",sideEffect:false},{tool:"tag_manager",operations:["publish"],agents:["analytics"],approval:"always",sideEffect:true},{tool:"maps",operations:["geocode","places"],agents:["sales","website-architect","seo","marketing"],approval:"never",sideEffect:false},
{tool:"whatsapp",operations:["draft"],agents:["support","client-journey","marketing"],approval:"never",sideEffect:false},{tool:"whatsapp",operations:["send"],agents:["support","client-journey","marketing"],approval:"always",sideEffect:true},{tool:"resend",operations:["send"],agents:["support","client-journey","marketing"],approval:"always",sideEffect:true},{tool:"twilio",operations:["send_sms"],agents:["support","client-journey"],approval:"always",sideEffect:true},
{tool:"crm",operations:["read"],agents:["ceo","sales","client-journey","support","finance","analytics","crm"],approval:"never",sideEffect:false},{tool:"crm",operations:["upsert"],agents:["sales","client-journey","support","finance","crm"],approval:"writes",sideEffect:true},
{tool:"stripe",operations:["invoice_draft","payment_link","refund"],agents:["finance"],approval:"always",sideEffect:true},{tool:"paypal",operations:["order_draft","refund"],agents:["finance"],approval:"always",sideEffect:true},
{tool:"n8n",operations:["execute"],agents:["automation"],approval:"always",sideEffect:true},{tool:"make",operations:["trigger"],agents:["automation"],approval:"always",sideEffect:true},{tool:"github",operations:["read","create_release"],agents:["frontend-builder","backend","qa","deployment"],approval:"writes",sideEffect:true},{tool:"gcp",operations:["cloud_build","cloud_run_deploy"],agents:["firebase","deployment"],approval:"always",sideEffect:true},
{tool:"storage",operations:["write_artifact"],agents:["client-journey","website-architect","ui-ux-designer","frontend-builder","backend","firebase","seo","content","brand","media","qa","deployment"],approval:"never",sideEffect:true},{tool:"firestore",operations:["read"],agents:all,approval:"never",sideEffect:false}
];
export function getToolPolicy(tool:string,operation:string,agentId:AgentId):ToolPolicy {const policy=toolPolicies.find((entry)=>entry.tool===tool&&entry.operations.includes(operation)&&entry.agents.includes(agentId));if(!policy)throw new Error(`Agent ${agentId} is not authorized for ${tool}.${operation}`);return policy;}
