import { Router, type Response } from "express";
import { canEditContentField, contentField, defaultWebsiteContentValues, updateContentPermissionsSchema, validateContentFieldValue, websiteContentFields, websiteContentSections } from "@pageloom/core";
import { z } from "zod";
import { customerPermission, requirePlatformAdmin, requirePlatformOrRole, requirePlatformProjectAccess, type AuthenticatedRequest } from "./auth.js";
import { db, storage } from "./firebase.js";

export const websiteContentRouter = Router();
const base = z.object({ organizationId: z.string().min(1) });
const draftSchema = base.extend({ values: z.record(z.string(), z.unknown()) });
const root = (org: string, site: string) => `organizations/${org}/websites/${site}/content`;
const submission = (org: string, site: string) => db.doc(`organizations/${org}/websites/${site}/contentSubmissions/current`);
const revisions = (org: string, site: string) => db.collection(`organizations/${org}/websites/${site}/contentRevisions`);

websiteContentRouter.get("/projects/:projectId/website-content", async (req: AuthenticatedRequest, res) => {
  try {
    const organizationId = z.string().min(1).parse(req.query.organizationId), projectId = String(req.params.projectId), member = await requirePlatformProjectAccess(req, res, organizationId, projectId); if (!member) return;
    const scope = await resolveWebsite(organizationId, projectId); if (!scope) return res.json({ data: empty(projectId) });
    const path = root(organizationId, scope.website.id), [permissions, draft, published, current] = await Promise.all([db.doc(`${path}/permissions`).get(), db.doc(`${path}/draft`).get(), db.doc(`${path}/published`).get(), submission(organizationId, scope.website.id).get()]);
    if (!permissions.exists) return res.json({ data: { ...empty(projectId), websiteId: scope.website.id, customerId: scope.project.customerId } });
    const config = permissions.data()!, isClient = member.role === "client";
    const fields = websiteContentFields.filter(field => !isClient || config.fields?.[field.id] === true).map(field => ({ ...field, customerEditable: config.fields?.[field.id] === true, locked: config.fields?.[field.id] !== true, section: field.sectionId, maxLength: field.maxLength ?? 20_000 }));
    const scoped = scopeValues(config, isClient);
    return res.json({ data: { configured: true, websiteId: scope.website.id, projectId, customerId: scope.project.customerId, publishMode: config.publishMode, status: current.data()?.status ?? draft.data()?.status ?? "draft", version: Number(published.data()?.version ?? 0), fields, sections: websiteContentSections, draft: scoped(draft.data()?.values ?? {}), published: scoped(published.data()?.values ?? {}), updatedAt: draft.data()?.updatedAt, canPublish: !isClient || config.publishMode === "direct" } });
  } catch (error) { return fail(res, error); }
});

websiteContentRouter.put("/projects/:projectId/website-content/config", async (req: AuthenticatedRequest, res) => {
  try {
    const input = updateContentPermissionsSchema.parse(req.body), projectId = String(req.params.projectId); if (!await requirePlatformOrRole(req, res, input.organizationId, ["owner", "admin"])) return;
    const project = await db.doc(`organizations/${input.organizationId}/projects/${projectId}`).get(); if (!project.exists || !project.data()?.customerId) return res.status(404).json({ error: { code: "PROJECT_NOT_FOUND", message: "Project not found" } });
    for (const key of Object.keys(input.fields)) contentField(key);
    const sites = await db.collection(`organizations/${input.organizationId}/websites`).where("projectId", "==", projectId).limit(1).get(), site = sites.docs[0]?.ref ?? db.doc(`organizations/${input.organizationId}/websites/${projectId}`), path = root(input.organizationId, site.id);
    const [draft, published] = await Promise.all([db.doc(`${path}/draft`).get(), db.doc(`${path}/published`).get()]), now = new Date().toISOString(), batch = db.batch();
    batch.set(site, { id: site.id, organizationId: input.organizationId, customerId: project.data()!.customerId, projectId, name: project.data()!.name, publicContentEnabled: true, ...(sites.empty ? { status: "development", createdAt: now } : {}), updatedAt: now }, { merge: true });
    batch.set(db.doc(`${path}/permissions`), { id: "permissions", ...input, customerId: project.data()!.customerId, projectId, websiteId: site.id, updatedBy: req.user!.uid, updatedAt: now }, { merge: true });
    if (!draft.exists) batch.create(db.doc(`${path}/draft`), { id: "draft", values: defaultWebsiteContentValues(), status: "draft", organizationId: input.organizationId, customerId: project.data()!.customerId, projectId, websiteId: site.id, updatedBy: req.user!.uid, updatedAt: now });
    if (!published.exists) batch.create(db.doc(`${path}/published`), { id: "published", values: {}, version: 0, organizationId: input.organizationId, customerId: project.data()!.customerId, projectId, websiteId: site.id, updatedBy: req.user!.uid, updatedAt: now });
    await batch.commit(); await record(input.organizationId, "website_content.permissions_updated", req.user!.uid, { projectId, websiteId: site.id }); return res.json({ data: { configured: true, websiteId: site.id, publishMode: input.publishMode } });
  } catch (error) { return fail(res, error); }
});

websiteContentRouter.put("/projects/:projectId/website-content/draft", async (req: AuthenticatedRequest, res) => {
  try {
    const input = draftSchema.parse(req.body), projectId = String(req.params.projectId), member = await requirePlatformProjectAccess(req, res, input.organizationId, projectId); if (!member) return;
    if (!customerPermission(member, "contentEdit")) return res.status(403).json({ error: { code: "CONTENT_PERMISSION_REQUIRED", message: "Website content editing is disabled for this portal user" } });
    const scope = await resolveWebsite(input.organizationId, projectId); if (!scope) return notConfigured(res);
    const path = root(input.organizationId, scope.website.id), [permissions, draft] = await Promise.all([db.doc(`${path}/permissions`).get(), db.doc(`${path}/draft`).get()]); if (!permissions.exists || !draft.exists) return notConfigured(res);
    const clean: Record<string, unknown> = {}, changes: { fieldId: string; previousValue: unknown; newValue: unknown }[] = [];
    for (const [fieldId, raw] of Object.entries(input.values)) { if (!canEditContentField(fieldId, member.role !== "client", permissions.data()!.fields ?? {})) return res.status(403).json({ error: { code: "PROTECTED_CONTENT_FIELD", message: `Website content field is protected: ${fieldId}` } }); const value = validateContentFieldValue(fieldId, raw); validateMedia(value, fieldId, input.organizationId, scope.project.customerId, projectId, scope.website.id); clean[fieldId] = value; if (JSON.stringify(draft.data()!.values?.[fieldId]) !== JSON.stringify(value)) changes.push({ fieldId, previousValue: draft.data()!.values?.[fieldId] ?? null, newValue: value }); }
    const values = { ...(draft.data()!.values ?? {}), ...clean }, now = new Date().toISOString(), batch = db.batch(); batch.set(db.doc(`${path}/draft`), { values, status: "draft", updatedBy: req.user!.uid, updatedByRole: member.role, updatedAt: now }, { merge: true });
    for (const change of changes) { const revision = revisions(input.organizationId, scope.website.id).doc(); batch.create(revision, { id: revision.id, type: "field_change", ...change, status: "draft", actorId: req.user!.uid, actorRole: member.role, createdAt: now }); }
    await batch.commit(); await record(input.organizationId, "website_content.draft_saved", req.user!.uid, { projectId, websiteId: scope.website.id, changedFields: changes.map(item => item.fieldId) }); return res.json({ data: { websiteId: scope.website.id, status: "draft", changed: changes.length, draft: scopeValues(permissions.data()!, member.role === "client")(values) } });
  } catch (error) { return fail(res, error); }
});

websiteContentRouter.get("/projects/:projectId/website-content/preview", async (req: AuthenticatedRequest, res) => {
  try { const organizationId = z.string().min(1).parse(req.query.organizationId), projectId = String(req.params.projectId), member = await requirePlatformProjectAccess(req, res, organizationId, projectId); if (!member) return; const scope = await resolveWebsite(organizationId, projectId); if (!scope) return notConfigured(res); const path = root(organizationId, scope.website.id), [permissions, draft] = await Promise.all([db.doc(`${path}/permissions`).get(), db.doc(`${path}/draft`).get()]); if (!draft.exists) return notConfigured(res); const scoped = permissions.exists ? scopeValues(permissions.data()!, member.role === "client")(draft.data()?.values ?? {}) : draft.data()?.values ?? {}; return res.json({ data: { organizationId, projectId, websiteId: scope.website.id, source: "draft", updatedAt: draft.data()?.updatedAt, values: await mediaUrls(scoped, organizationId, scope.project.customerId, projectId, scope.website.id) } }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.post("/projects/:projectId/website-content/submit", async (req: AuthenticatedRequest, res) => {
  try { const input = base.parse(req.body), projectId = String(req.params.projectId), member = await requirePlatformProjectAccess(req, res, input.organizationId, projectId); if (!member) return; const scope = await resolveWebsite(input.organizationId, projectId); if (!scope) return notConfigured(res); const path = root(input.organizationId, scope.website.id), [draft, published] = await Promise.all([db.doc(`${path}/draft`).get(), db.doc(`${path}/published`).get()]); if (!draft.exists) return notConfigured(res); const values = draft.data()!.values ?? {}, changedFields = websiteContentFields.map(field => field.id).filter(fieldId => JSON.stringify(values[fieldId]) !== JSON.stringify(published.data()?.values?.[fieldId])); if (!changedFields.length) return res.status(409).json({ error: { code: "NO_CONTENT_CHANGES", message: "There are no unpublished changes to submit" } }); const now = new Date().toISOString(), batch = db.batch(); batch.set(submission(input.organizationId, scope.website.id), { id: "current", status: "pending", fieldIds: changedFields, values, organizationId: input.organizationId, customerId: scope.project.customerId, projectId, websiteId: scope.website.id, submittedBy: req.user!.uid, submittedAt: now }); batch.create(db.collection(`organizations/${input.organizationId}/notifications`).doc(), { audience: "owner", title: "Website content submitted", body: `Content for ${scope.website.name ?? scope.project.name ?? scope.website.id} is ready for review.`, projectId, websiteId: scope.website.id, customerId: scope.project.customerId, type: "website_content_submitted", read: false, createdAt: now }); await batch.commit(); await record(input.organizationId, "website_content.submitted", req.user!.uid, { projectId, websiteId: scope.website.id, changedFields }); return res.json({ data: { status: "pending", websiteId: scope.website.id, changedFields } }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.get("/projects/:projectId/website-content/revisions", async (req: AuthenticatedRequest, res) => {
  try { const organizationId = z.string().min(1).parse(req.query.organizationId), projectId = String(req.params.projectId); if (!await requirePlatformOrRole(req, res, organizationId, ["owner", "admin"])) return; const scope = await resolveWebsite(organizationId, projectId); if (!scope) return notConfigured(res); const snapshot = await revisions(organizationId, scope.website.id).orderBy("createdAt", "desc").limit(100).get(); return res.json({ data: snapshot.docs.map(doc => ({ id: doc.id, ...doc.data() })) }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.get("/projects/:projectId/website-content/revisions/:revisionId", async (req: AuthenticatedRequest, res) => {
  try { const organizationId = z.string().min(1).parse(req.query.organizationId), projectId = String(req.params.projectId); if (!await requirePlatformOrRole(req, res, organizationId, ["owner", "admin"])) return; const scope = await resolveWebsite(organizationId, projectId); if (!scope) return notConfigured(res); const snapshot = await revisions(organizationId, scope.website.id).doc(String(req.params.revisionId)).get(); if (!snapshot.exists) return res.status(404).json({ error: { code: "REVISION_NOT_FOUND", message: "Revision not found" } }); const revision = snapshot.data()!; const values = revision.values ? await mediaUrls(revision.values, organizationId, scope.project.customerId, projectId, scope.website.id) : undefined; return res.json({ data: { id: snapshot.id, ...revision, ...(values ? { values } : {}) } }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.post("/projects/:projectId/website-content/decision", async (req: AuthenticatedRequest, res) => {
  try { const input = base.extend({ decision: z.enum(["approved", "rejected", "changes_requested"]), reason: z.string().max(2000).optional() }).refine(value => value.decision === "approved" || Boolean(value.reason?.trim()), { message: "A reason is required" }).parse(req.body), projectId = String(req.params.projectId), administrator = await requirePlatformOrRole(req, res, input.organizationId, ["owner", "admin"]); if (!administrator) return; const scope = await resolveWebsite(input.organizationId, projectId); if (!scope) return notConfigured(res); const current = await submission(input.organizationId, scope.website.id).get(); if (!current.exists || current.data()?.status !== "pending") return res.status(409).json({ error: { code: "CONTENT_NOT_SUBMITTED", message: "Only pending content can be reviewed" } }); if (input.decision === "approved") return publish(res, { organizationId: input.organizationId, projectId, websiteId: scope.website.id, customerId: scope.project.customerId, actorId: req.user!.uid, actorRole: String(administrator.role), approval: true }); const now = new Date().toISOString(), batch = db.batch(); batch.update(current.ref, { status: input.decision, reason: input.reason!.trim(), decidedBy: req.user!.uid, decidedAt: now }); batch.create(db.collection(`organizations/${input.organizationId}/notifications`).doc(), { audience: "customer", customerId: scope.project.customerId, projectId, websiteId: scope.website.id, title: input.decision === "changes_requested" ? "Website content returned for changes" : "Website content rejected", body: input.reason!.trim(), type: `website_content_${input.decision}`, read: false, createdAt: now }); await batch.commit(); await record(input.organizationId, `website_content.${input.decision}`, req.user!.uid, { projectId, websiteId: scope.website.id, reason: input.reason!.trim() }); return res.json({ data: { status: input.decision } }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.post("/projects/:projectId/website-content/publish", async (req: AuthenticatedRequest, res) => {
  try { const input = base.parse(req.body), projectId = String(req.params.projectId), member = await requirePlatformProjectAccess(req, res, input.organizationId, projectId); if (!member) return; const scope = await resolveWebsite(input.organizationId, projectId); if (!scope) return notConfigured(res); const permissions = await db.doc(`${root(input.organizationId, scope.website.id)}/permissions`).get(); if (!permissions.exists) return notConfigured(res); if (member.role === "client" && permissions.data()?.publishMode !== "direct") return res.status(403).json({ error: { code: "OWNER_APPROVAL_REQUIRED", message: "This website requires PageLoom approval before publishing" } }); return publish(res, { organizationId: input.organizationId, projectId, websiteId: scope.website.id, customerId: scope.project.customerId, actorId: req.user!.uid, actorRole: String(member.role), approval: false }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.post("/projects/:projectId/website-content/rollback", async (req: AuthenticatedRequest, res) => {
  try { const input = base.extend({ revisionId: z.string().min(1) }).parse(req.body), projectId = String(req.params.projectId); if (!await requirePlatformOrRole(req, res, input.organizationId, ["owner"])) return; const scope = await resolveWebsite(input.organizationId, projectId); if (!scope) return notConfigured(res); const source = await revisions(input.organizationId, scope.website.id).doc(input.revisionId).get(); if (!source.exists || source.data()?.type !== "snapshot") return res.status(409).json({ error: { code: "REVISION_NOT_ROLLBACKABLE", message: "Revision does not contain a published snapshot" } }); const path = root(input.organizationId, scope.website.id), published = await db.doc(`${path}/published`).get(), now = new Date().toISOString(), version = Number(published.data()?.version ?? 0) + 1, revision = revisions(input.organizationId, scope.website.id).doc(), batch = db.batch(); batch.set(db.doc(`${path}/draft`), { values: source.data()!.values, status: "draft", updatedBy: req.user!.uid, updatedAt: now }, { merge: true }); batch.set(db.doc(`${path}/published`), { values: source.data()!.values, version, updatedBy: req.user!.uid, updatedAt: now }, { merge: true }); batch.create(revision, { id: revision.id, type: "snapshot", reason: "rollback", values: source.data()!.values, sourceRevisionId: input.revisionId, version, actorId: req.user!.uid, actorRole: "owner", createdAt: now }); await batch.commit(); await record(input.organizationId, "website_content.rolled_back", req.user!.uid, { projectId, websiteId: scope.website.id, sourceRevisionId: input.revisionId, version }); return res.json({ data: { status: "published", version, revisionId: revision.id } }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.delete("/projects/:projectId/website-content/media", async (req: AuthenticatedRequest, res) => {
  try { const input = base.extend({ path: z.string().min(1).max(1000) }).parse(req.body), projectId = String(req.params.projectId), member = await requirePlatformProjectAccess(req, res, input.organizationId, projectId); if (!member) return; const scope = await resolveWebsite(input.organizationId, projectId); if (!scope) return notConfigured(res); const prefix = `organizations/${input.organizationId}/website-media/${scope.project.customerId}/${projectId}/${scope.website.id}/`; if (!input.path.startsWith(prefix) || (member.role === "client" && !input.path.startsWith(`${prefix}${req.user!.uid}/`))) return res.status(403).json({ error: { code: "MEDIA_DELETE_FORBIDDEN", message: "Media does not belong to this user and website" } }); const path = root(input.organizationId, scope.website.id), [draft, published] = await Promise.all([db.doc(`${path}/draft`).get(), db.doc(`${path}/published`).get()]); if (contains(draft.data()?.values, input.path) || contains(published.data()?.values, input.path)) return res.status(409).json({ error: { code: "MEDIA_IN_USE", message: "Remove this media from draft and published content before deleting it" } }); await storage.bucket().file(input.path).delete({ ignoreNotFound: true }); await record(input.organizationId, "website_content.media_deleted", req.user!.uid, { projectId, websiteId: scope.website.id, path: input.path }); return res.json({ data: { deleted: true, path: input.path } }); } catch (error) { return fail(res, error); }
});

websiteContentRouter.get("/platform/content-submissions", async (req: AuthenticatedRequest, res) => {
  try { if (!await requirePlatformAdmin(req, res)) return; const organizations = await db.collection("organizations").limit(200).get(), items: Record<string, unknown>[] = []; for (const organization of organizations.docs) { const websites = await organization.ref.collection("websites").limit(1000).get(); if (websites.empty) continue; const snapshots = await db.getAll(...websites.docs.map(website => submission(organization.id, website.id))); snapshots.forEach((item, index) => { if (item.exists && item.data()?.status === "pending") { const website = websites.docs[index]!; items.push({ id: item.id, ...item.data(), organizationName: organization.data().name ?? organization.id, websiteName: website.data().name ?? website.id }); } }); } items.sort((a, b) => String(b.submittedAt).localeCompare(String(a.submittedAt))); return res.json({ data: items }); } catch (error) { return fail(res, error); }
});

// A customer must only ever receive values for fields explicitly marked customer-editable in the
// website's permissions doc — protected fields (e.g. SEO metadata) must not leak through a raw
// draft/published/preview payload even though the editing UI never renders a control for them.
function scopeValues(config: FirebaseFirestore.DocumentData, isClient: boolean) {
  const visibleIds = new Set(websiteContentFields.filter(field => !isClient || config.fields?.[field.id] === true).map(field => field.id));
  return (values: Record<string, unknown>) => isClient ? Object.fromEntries(Object.entries(values).filter(([id]) => visibleIds.has(id))) : values;
}
async function resolveWebsite(organizationId: string, projectId: string) { const project = await db.doc(`organizations/${organizationId}/projects/${projectId}`).get(); if (!project.exists) return; const sites = await db.collection(`organizations/${organizationId}/websites`).where("projectId", "==", projectId).limit(1).get(), website = sites.docs[0]; if (!website) return; return { project: { id: project.id, ...project.data() } as FirebaseFirestore.DocumentData, website: { id: website.id, ...website.data() } as FirebaseFirestore.DocumentData }; }
async function publish(res: Response, scope: { organizationId: string; projectId: string; websiteId: string; customerId: string; actorId: string; actorRole: string; approval: boolean }) { const path = root(scope.organizationId, scope.websiteId), [draft, published, current] = await Promise.all([db.doc(`${path}/draft`).get(), db.doc(`${path}/published`).get(), submission(scope.organizationId, scope.websiteId).get()]); if (!draft.exists) return notConfigured(res); const values = scope.approval ? current.data()?.values : draft.data()?.values; if (!values) return res.status(409).json({ error: { code: "EMPTY_DRAFT", message: "No draft is available to publish" } }); const now = new Date().toISOString(), version = Number(published.data()?.version ?? 0) + 1, revision = revisions(scope.organizationId, scope.websiteId).doc(), batch = db.batch(); batch.set(db.doc(`${path}/published`), { values, version, organizationId: scope.organizationId, customerId: scope.customerId, projectId: scope.projectId, websiteId: scope.websiteId, updatedBy: scope.actorId, updatedAt: now }, { merge: true }); batch.create(revision, { id: revision.id, type: "snapshot", reason: scope.approval ? "approve" : "publish", values, version, actorId: scope.actorId, actorRole: scope.actorRole, createdAt: now }); if (scope.approval && current.exists) batch.update(current.ref, { status: "approved", decidedBy: scope.actorId, decidedAt: now }); batch.create(db.collection(`organizations/${scope.organizationId}/notifications`).doc(), { audience: "customer", customerId: scope.customerId, projectId: scope.projectId, websiteId: scope.websiteId, title: "Website content published", body: `Content version ${version} is now published.`, type: "website_content_published", read: false, createdAt: now }); await batch.commit(); await record(scope.organizationId, "website_content.published", scope.actorId, { projectId: scope.projectId, websiteId: scope.websiteId, revisionId: revision.id, version }); return res.json({ data: { status: "published", version, revisionId: revision.id } }); }
function validateMedia(value: unknown, fieldId: string, org: string, customer: string, project: string, site: string) { const field = contentField(fieldId); if (!["image", "gallery", "videos"].includes(field.type)) return; const prefix = `organizations/${org}/website-media/${customer}/${project}/${site}/`, paths = field.type === "image" ? [value] : field.type === "gallery" ? value : (value as { type: string; value: string }[]).filter(item => item.type === "upload").map(item => item.value); for (const path of paths as unknown[]) if (typeof path === "string" && path && !path.startsWith(prefix)) throw new Error("Media must belong to the same customer, project, and website"); }
function contains(value: unknown, path: string): boolean { if (value === path) return true; if (Array.isArray(value)) return value.some(item => contains(item, path)); if (value && typeof value === "object") return Object.values(value as Record<string, unknown>).some(item => contains(item, path)); return false; }
async function mediaUrls(values: Record<string, unknown>, org: string, customer: string, project: string, site: string) { const prefix = `organizations/${org}/website-media/${customer}/${project}/${site}/`; async function visit(value: unknown): Promise<unknown> { if (typeof value === "string" && value.startsWith(prefix)) { const [url] = await storage.bucket().file(value).getSignedUrl({ action: "read", expires: Date.now() + 15 * 60_000 }); return url; } if (Array.isArray(value)) return Promise.all(value.map(visit)); if (value && typeof value === "object") return Object.fromEntries(await Promise.all(Object.entries(value as Record<string, unknown>).map(async ([key, item]) => [key, await visit(item)]))); return value; } return await visit(values) as Record<string, unknown>; }
async function record(organizationId: string, type: string, actorId: string, payload: Record<string, unknown>) { await db.collection(`organizations/${organizationId}/activity`).add({ type, actorId, customerId: payload.customerId ?? null, projectId: payload.projectId ?? null, websiteId: payload.websiteId ?? null, payload, createdAt: new Date().toISOString() }); }
function empty(projectId: string) { return { configured: false, projectId, status: "not_configured", fields: [], sections: [], draft: {}, published: {} }; }
function notConfigured(res: Response) { return res.status(409).json({ error: { code: "CONTENT_NOT_CONFIGURED", message: "Website content must be configured by an administrator first" } }); }
function fail(res: Response, error: unknown) { if (error instanceof z.ZodError) return res.status(422).json({ error: { code: "VALIDATION_ERROR", message: "Website content validation failed", issues: error.issues } }); return res.status(400).json({ error: { code: "WEBSITE_CONTENT_ERROR", message: error instanceof Error ? error.message : "Website content operation failed" } }); }
