import { z } from "zod";
import { launchBusinessRules, type BusinessRules } from "./business-rules.js";

export const businessAutomationSnapshotSchema = z.object({ domains: z.array(z.object({ id: z.string(), name: z.string(), expiresAt: z.string().datetime() })).default([]), certificates: z.array(z.object({ id: z.string(), domain: z.string(), expiresAt: z.string().datetime() })).default([]), backups: z.array(z.object({ id: z.string(), resourceId: z.string(), status: z.string(), createdAt: z.string().datetime() })).default([]), customers: z.array(z.object({ id: z.string(), name: z.string(), lastActivityAt: z.string().datetime() })).default([]), projects: z.array(z.object({ id: z.string(), name: z.string(), status: z.string(), updatedAt: z.string().datetime(), revenue: z.number().default(0), cost: z.number().default(0) })).default([]) });
export type BusinessAlert = { key: string; severity: "warning" | "critical"; type: "domain_expiry" | "ssl_expiry" | "backup_failure" | "customer_inactivity" | "project_stalled" | "negative_profitability"; title: string; body: string; params: Record<string, unknown>; resourceId: string; dueAt?: string };

export function evaluateBusinessAutomations(input: z.infer<typeof businessAutomationSnapshotSchema>, now = new Date(), rules: BusinessRules = launchBusinessRules) {
  const alerts: BusinessAlert[] = [], days = (date: string) => (Date.parse(date) - now.getTime()) / 86_400_000, stale = (date: string) => (now.getTime() - Date.parse(date)) / 86_400_000;
  for (const item of input.domains) if (days(item.expiresAt) <= rules.hosting.domainExpiryWarningDays) alerts.push({ key: `domain_expiry:${item.id}:${item.expiresAt}`, severity: days(item.expiresAt) <= 7 ? "critical" : "warning", type: "domain_expiry", title: `Domain expires in ${Math.ceil(days(item.expiresAt))} days`, body: item.name, params: { domain: item.name, daysRemaining: Math.ceil(days(item.expiresAt)) }, resourceId: item.id, dueAt: item.expiresAt });
  for (const item of input.certificates) if (days(item.expiresAt) <= rules.hosting.sslExpiryWarningDays) alerts.push({ key: `ssl_expiry:${item.id}:${item.expiresAt}`, severity: days(item.expiresAt) <= 3 ? "critical" : "warning", type: "ssl_expiry", title: `SSL expires in ${Math.ceil(days(item.expiresAt))} days`, body: item.domain, params: { domain: item.domain, daysRemaining: Math.ceil(days(item.expiresAt)) }, resourceId: item.id, dueAt: item.expiresAt });
  for (const item of input.backups.filter(item => item.status === "failed")) alerts.push({ key: `backup_failure:${item.id}`, severity: "critical", type: "backup_failure", title: "Backup failed", body: `Resource ${item.resourceId} requires recovery review`, params: { resourceId: item.resourceId }, resourceId: item.resourceId });
  for (const item of input.customers) if (stale(item.lastActivityAt) >= rules.lifecycle.customerInactivityWarningDays) alerts.push({ key: `customer_inactivity:${item.id}:${item.lastActivityAt}`, severity: "warning", type: "customer_inactivity", title: "Customer inactive", body: `${item.name} has been inactive for ${Math.floor(stale(item.lastActivityAt))} days`, params: { customerName: item.name, daysInactive: Math.floor(stale(item.lastActivityAt)) }, resourceId: item.id });
  for (const item of input.projects.filter(item => !["completed", "cancelled"].includes(item.status))) { if (stale(item.updatedAt) >= rules.project.inactivityDaysBeforeStalled) alerts.push({ key: `project_stalled:${item.id}:${item.updatedAt}`, severity: "warning", type: "project_stalled", title: "Project stalled", body: `${item.name} has no verified activity`, params: { projectName: item.name }, resourceId: item.id }); if (item.revenue - item.cost < 0) alerts.push({ key: `negative_profitability:${item.id}:${item.revenue}:${item.cost}`, severity: "critical", type: "negative_profitability", title: "Project profitability is negative", body: `${item.name}: ${item.revenue - item.cost}`, params: { projectName: item.name, deficit: item.revenue - item.cost }, resourceId: item.id }); }
  return alerts;
}
