import { salesPackages, type SalesPackage } from "./sales-enablement.js";
export type ClosingProposal = { id: string; customer: string; business: string; package: SalesPackage; challenge: string; investment: number; deposit: number; balance: number; validUntil: string; status: "draft"|"sent"|"accepted"|"expired" };
export function createClosingProposal(input:{customer:string;business:string;packageId:SalesPackage["id"];challenge:string;validUntil:string}):ClosingProposal { const plan=salesPackages.find(item=>item.id===input.packageId); if(!plan||!input.customer.trim()||!input.business.trim()||!input.challenge.trim()||Date.parse(input.validUntil)<=Date.now())throw new Error("Complete a valid proposal");const deposit=plan.price*plan.depositPercent/100;return{id:crypto.randomUUID(),customer:input.customer.trim(),business:input.business.trim(),package:plan,challenge:input.challenge.trim(),investment:plan.price,deposit,balance:plan.price-deposit,validUntil:input.validUntil,status:"draft"}; }
export type ContractAcceptance={proposalId:string;customerName:string;agreementVersion:string;acceptedTerms:boolean;typedSignature:string;acceptedAt:string};
export function acceptDigitalContract(input:Omit<ContractAcceptance,"acceptedAt">,now=new Date()):ContractAcceptance{if(!input.acceptedTerms||input.typedSignature.trim()!==input.customerName.trim()||!/^\d+\.\d+$/.test(input.agreementVersion))throw new Error("Valid consent and matching signature are required");return{...input,typedSignature:input.typedSignature.trim(),acceptedAt:now.toISOString()}}
export type ClosingChecklistItem={id:string;label:string;owner:"customer"|"owner";required:boolean;complete:boolean};
export function onboardingChecklist():ClosingChecklistItem[]{return[{id:"contract",label:"Contract signed",owner:"customer",required:true,complete:false},{id:"deposit",label:"Deposit received",owner:"customer",required:true,complete:false},{id:"questionnaire",label:"Business questionnaire completed",owner:"customer",required:true,complete:false},{id:"assets",label:"Brand assets uploaded",owner:"customer",required:true,complete:false},{id:"kickoff",label:"Kickoff call scheduled",owner:"owner",required:true,complete:false}]}
export type Payment={id:string;label:string;amount:number;dueAt:string;paidAt?:string;status:"pending"|"paid"|"overdue"};
export function paymentSchedule(proposal:ClosingProposal,startAt:string):Payment[]{const start=new Date(startAt);if(Number.isNaN(start.getTime()))throw new Error("Valid payment start date required");const balanceDue=new Date(start);balanceDue.setDate(balanceDue.getDate()+proposal.package.timelineWeeks*7);return[{id:"deposit",label:"Project deposit",amount:proposal.deposit,dueAt:start.toISOString(),status:"pending"},{id:"balance",label:"Final balance",amount:proposal.balance,dueAt:balanceDue.toISOString(),status:"pending"}]}
export function markPaymentPaid(payment:Payment,paidAt=new Date()):Payment{return{...payment,paidAt:paidAt.toISOString(),status:"paid"}}
export type KickoffAction={id:string;owner:"owner"|"customer"|"system";title:string;dueDay:number};
export function kickoffAutomation(customer:string):KickoffAction[]{if(!customer.trim())throw new Error("Customer required");return[{id:"welcome",owner:"system",title:`Send ${customer} the welcome portal`,dueDay:0},{id:"workspace",owner:"owner",title:"Create project workspace and confirm scope",dueDay:0},{id:"questionnaire",owner:"customer",title:"Complete questionnaire and uploads",dueDay:2},{id:"call",owner:"owner",title:"Run kickoff call and approve delivery plan",dueDay:3}]}
export function customerTimeline(startAt:string,weeks:number){const start=new Date(startAt);if(Number.isNaN(start.getTime())||weeks<1)throw new Error("Valid timeline required");const point=(label:string,day:number)=>({label,date:new Date(start.getTime()+day*86400000).toISOString()});return[point("Payment and welcome",0),point("Discovery complete",3),point("Direction approved",7),point("Build and review",Math.max(8,weeks*7-7)),point("Launch target",weeks*7)]}
export function ownerTasksAfterPayment(customer:string):KickoffAction[]{return kickoffAutomation(customer).filter(item=>item.owner==="owner").concat([{id:"receipt",owner:"owner",title:"Confirm payment receipt and invoice record",dueDay:0},{id:"handoff",owner:"owner",title:"Review signed scope before production handoff",dueDay:1}])}
