import{z}from"zod";

export const documentTypeSchema=z.enum(["customer_agreement","proposal","questionnaire","design_approval","development_approval","pre_launch_approval","website_delivery","maintenance_agreement","privacy_policy","accessibility_statement","terms_of_service","data_processing_agreement","internal_notes"]);
export const documentAudienceSchema=z.enum(["customer","internal"]);
export const documentStatusSchema=z.enum(["draft","pending_signature","signed","approved","published","superseded","void"]);
export const documentFormatSchema=z.enum(["html","pdf"]);
export const documentTemplateSchema=z.object({id:z.string().min(1).max(120),type:documentTypeSchema,name:z.string().min(2).max(200),locale:z.string().regex(/^[a-z]{2}(?:-[A-Z]{2})?$/).default("he"),direction:z.enum(["rtl","ltr"]).default("rtl"),audience:documentAudienceSchema,version:z.number().int().positive(),titleTemplate:z.string().min(2).max(500),bodyTemplate:z.string().min(10).max(500_000),requiredVariables:z.array(z.string().regex(/^[a-zA-Z][a-zA-Z0-9_.]*$/)).max(100).default([]),status:z.enum(["draft","active","retired"]).default("draft")});
export const documentVersionSchema=z.object({id:z.string().min(1),organizationId:z.string().min(1),projectId:z.string().min(1).optional(),customerId:z.string().min(1).optional(),templateId:z.string().min(1),type:documentTypeSchema,audience:documentAudienceSchema,version:z.number().int().positive(),locale:z.string().min(2).default("he"),direction:z.enum(["rtl","ltr"]).default("rtl"),title:z.string().min(2),html:z.string().min(20),contentHash:z.string().regex(/^[a-f0-9]{64}$/),status:documentStatusSchema,createdAt:z.string().datetime(),createdBy:z.string().min(1)});
export const digitalSignatureSchema=z.object({documentId:z.string().min(1),documentVersion:z.number().int().positive(),documentHash:z.string().regex(/^[a-f0-9]{64}$/),signerId:z.string().min(1),signerName:z.string().min(2).max(200),signerRole:z.enum(["customer","owner","witness"]),intentText:z.string().min(10).max(2000),signedAt:z.string().datetime(),ipHash:z.string().regex(/^[a-f0-9]{64}$/),userAgentHash:z.string().regex(/^[a-f0-9]{64}$/),signatureHash:z.string().regex(/^[a-f0-9]{64}$/)});
export type DocumentTemplate=z.infer<typeof documentTemplateSchema>;
export type DocumentVersion=z.infer<typeof documentVersionSchema>;
export type DigitalSignature=z.infer<typeof digitalSignatureSchema>;

function lookup(input:Record<string,unknown>,path:string){let value:unknown=input;for(const part of path.split(".")){if(!value||typeof value!=="object"||!(part in value))return undefined;value=(value as Record<string,unknown>)[part]}return value}
export function renderTemplate(template:DocumentTemplate,data:Record<string,unknown>){const missing=template.requiredVariables.filter(variable=>{const value=lookup(data,variable);return value===undefined||value===null||value===""});if(missing.length)throw new Error(`Missing document variables: ${missing.join(", ")}`);const render=(source:string)=>source.replace(/{{\s*([a-zA-Z][a-zA-Z0-9_.]*)\s*}}/g,(_match,key:string)=>{const value=lookup(data,key);if(value===undefined||value===null)throw new Error(`Unresolved document variable: ${key}`);return String(value)});const title=render(template.titleTemplate),body=render(template.bodyTemplate);if(template.locale==="he"&&template.audience==="customer"&&!/[\u0590-\u05ff]/.test(`${title} ${body}`))throw new Error("Hebrew customer documents must contain Hebrew text");return{title,body,locale:template.locale,direction:template.direction}}
export function nextDocumentVersion(existing:number[]){return existing.length?Math.max(...existing)+1:1}
export function signatureMatchesDocument(signature:DigitalSignature,document:DocumentVersion){return signature.documentId===document.id&&signature.documentVersion===document.version&&signature.documentHash===document.contentHash&&document.status!=="superseded"&&document.status!=="void"}
