import{z}from"zod";

export const customerLanguageSchema=z.literal("he").default("he");
export const customerDirectionSchema=z.literal("rtl").default("rtl");
const hebrewText=(maximum:number)=>z.string().min(2).max(maximum).refine(value=>/[\u0590-\u05ff]/.test(value),"Customer-facing text must contain Hebrew");
export const customerDocumentSchema=z.object({type:z.enum(["proposal","contract","legal","invoice","project_summary"]),version:z.string().regex(/^\d+\.\d+$/),title:hebrewText(200),content:hebrewText(500_000),locale:customerLanguageSchema,direction:customerDirectionSchema,status:z.enum(["draft","approved","published","superseded"]).default("draft")});
export const israeliEntityTypeSchema=z.enum(["osek_patur","osek_murshe","company","nonprofit","partnership"]);
export const israeliTaxProfileSchema=z.object({legalNameHebrew:z.string().min(2).max(200),businessNumber:z.string().regex(/^\d{9}$/),entityType:israeliEntityTypeSchema,currency:z.literal("ILS").default("ILS"),vatRegistered:z.boolean(),withholdingTaxCertificate:z.boolean().default(false),bookkeepingCertificate:z.boolean().default(false),invoiceProvider:z.string().max(100).optional(),invoiceProviderCustomerId:z.string().max(200).optional()});
export const israeliInvoiceDocumentTypeSchema=z.enum(["transaction_invoice","tax_invoice","receipt","tax_invoice_receipt","credit_note"]);
export const israeliInvoiceDraftSchema=z.object({customerId:z.string().min(1),projectId:z.string().min(1).optional(),documentType:israeliInvoiceDocumentTypeSchema,currency:z.literal("ILS").default("ILS"),locale:customerLanguageSchema,direction:customerDirectionSchema,vatRateBps:z.number().int().min(0).max(10_000),lines:z.array(z.object({descriptionHebrew:z.string().min(2).max(500),quantity:z.number().positive(),unitPriceAgorot:z.number().int().nonnegative()})).min(1).max(100),status:z.literal("draft").default("draft")});
export type IsraeliInvoiceDraft=z.infer<typeof israeliInvoiceDraftSchema>;
export function calculateIsraeliInvoice(draft:IsraeliInvoiceDraft){const subtotalAgorot=draft.lines.reduce((sum,line)=>sum+Math.round(line.quantity*line.unitPriceAgorot),0),vatAgorot=Math.round(subtotalAgorot*draft.vatRateBps/10_000);return{subtotalAgorot,vatAgorot,totalAgorot:subtotalAgorot+vatAgorot,currency:"ILS"as const}}

export const customerMessageTemplateSchema=z.enum(["onboarding_started","questionnaire_ready","approval_required","revision_received","website_published"]);
const messages:Record<z.infer<typeof customerMessageTemplateSchema>,{subject:string;body:(name:string,link?:string)=>string;whatsapp:(name:string,link?:string)=>string}>={
  onboarding_started:{subject:"ברוכים הבאים ל-PageLoom",body:name=>`שלום ${name},\n\nשמחים להתחיל את פרויקט האתר שלכם. בקרוב נשלח אליכם שאלון קצר ואזור מאובטח להעלאת החומרים.\n\nצוות PageLoom`,whatsapp:name=>`שלום ${name}, ברוכים הבאים ל-PageLoom. פרויקט האתר שלכם נפתח ונשלח אליכם בקרוב את השלב הבא.`},
  questionnaire_ready:{subject:"שאלון הפרויקט שלכם מוכן",body:(name,link)=>`שלום ${name},\n\nשאלון אפיון האתר מוכן למילוי. המידע שתמסרו ישמש לתכנון האתר ולהפקת התכנים.\n\nלשאלון: ${link??"היכנסו לפורטל הלקוחות"}`,whatsapp:(name,link)=>`שלום ${name}, שאלון אפיון האתר מוכן: ${link??"היכנסו לפורטל הלקוחות"}`},
  approval_required:{subject:"האתר מוכן לבדיקה ולאישור",body:(name,link)=>`שלום ${name},\n\nגרסת האתר מוכנה לבדיקה. אפשר לצפות בה, להשאיר הערות או לאשר דרך פורטל הלקוחות.\n\nלצפייה: ${link??"היכנסו לפורטל הלקוחות"}`,whatsapp:(name,link)=>`שלום ${name}, גרסת האתר מוכנה לבדיקה ולאישור: ${link??"היכנסו לפורטל הלקוחות"}`},
  revision_received:{subject:"בקשת השינויים התקבלה",body:name=>`שלום ${name},\n\nבקשת השינויים התקבלה והועברה לצוות הפרויקט. נעדכן אתכם כשהגרסה המעודכנת תהיה מוכנה.`,whatsapp:name=>`שלום ${name}, בקשת השינויים התקבלה והועברה לצוות. נעדכן כשהגרסה המעודכנת תהיה מוכנה.`},
  website_published:{subject:"האתר שלכם עלה לאוויר",body:(name,link)=>`שלום ${name},\n\nבשעה טובה, האתר שלכם עלה לאוויר.\n\nכתובת האתר: ${link??"זמינה בפורטל הלקוחות"}\n\nתודה שבחרתם ב-PageLoom.`,whatsapp:(name,link)=>`שלום ${name}, בשעה טובה—האתר שלכם עלה לאוויר: ${link??"הכתובת זמינה בפורטל הלקוחות"}`}
};
export function renderCustomerMessage(input:{template:z.infer<typeof customerMessageTemplateSchema>;channel:"email"|"whatsapp";customerName:string;link?:string}){const template=messages[input.template];return{locale:"he"as const,direction:"rtl"as const,channel:input.channel,...(input.channel==="email"?{subject:template.subject,body:template.body(input.customerName,input.link)}:{body:template.whatsapp(input.customerName,input.link)})}}
