import{z}from"zod";import type{AgentId}from"./types.js";
export const workflowStageSchema=z.enum(["lead","phone_call","won","questionnaire","assets","brand_strategy","website_architecture","ui_design","copywriting","development","seo","qa","customer_approval","deployment","maintenance"]);export type WorkflowStage=z.infer<typeof workflowStageSchema>;
export const workflowEventTypeSchema=z.enum(["LeadCreated","PhoneCallScheduled","PhoneCallCompleted","LeadWon","ProjectIntakeStarted","QuestionnaireCompleted","AssetsUploaded","AssetsValidated","BrandApproved","ArchitectureCompleted","UIDesignApproved","CopywritingCompleted","DevelopmentStarted","DevelopmentCompleted","SEOCompleted","QACompleted","QAFailed","WebsiteApproved","ApprovalRejected","DeploymentCompleted","MaintenanceStarted","AssetsMissing","StageTimedOut","AgentTaskFailed","ManualRetryRequested"]);export type WorkflowEventType=z.infer<typeof workflowEventTypeSchema>;
export type WorkflowCondition="leadExists"|"callCompleted"|"dealWon"|"questionnaireComplete"|"assetsComplete"|"brandApproved"|"architectureComplete"|"uiApproved"|"copyApproved"|"developmentComplete"|"seoComplete"|"qaPassed"|"websiteApproved"|"deploymentComplete";
export interface WorkflowStageDefinition{stage:WorkflowStage;entryConditions:WorkflowCondition[];exitEvents:WorkflowEventType[];requiredAgents:AgentId[];approval:"none"|"ceo"|"customer";timeoutMinutes:number;retry:{maxAttempts:number;backoffMinutes:number};notifications:("ceo"|"project_manager"|"customer")[];estimatedMinutes:number;rollbackStage?:WorkflowStage}
export const workflowOrder=workflowStageSchema.options;
export const workflowDefinitions:Record<WorkflowStage,WorkflowStageDefinition>={
 lead:d("lead",[],["PhoneCallScheduled"],["sales"],"none",1440,3,30,["ceo"],60),
 phone_call:d("phone_call",["leadExists"],["LeadWon"],["sales"],"ceo",2880,2,120,["ceo","project_manager"],60),
 won:d("won",["callCompleted","dealWon"],["ProjectIntakeStarted"],["project-manager"],"ceo",1440,3,60,["ceo","project_manager"],30),
 questionnaire:d("questionnaire",["dealWon"],["QuestionnaireCompleted"],["client-journey"],"none",4320,3,240,["project_manager","customer"],240),
 assets:{...d("assets",["questionnaireComplete"],["AssetsValidated"],["media","project-manager"],"none",4320,3,240,["project_manager","customer"],480),rollbackStage:"assets"},
 brand_strategy:d("brand_strategy",["assetsComplete"],["BrandApproved"],["brand"],"ceo",2880,2,120,["ceo","project_manager"],480),
 website_architecture:d("website_architecture",["brandApproved"],["ArchitectureCompleted"],["website-architect"],"none",1440,3,60,["project_manager"],360),
 ui_design:d("ui_design",["architectureComplete"],["UIDesignApproved"],["ui-ux-designer"],"ceo",2880,3,120,["ceo","project_manager"],720),
 copywriting:d("copywriting",["uiApproved"],["CopywritingCompleted"],["content"],"none",2880,3,120,["project_manager"],600),
 development:{...d("development",["copyApproved"],["DevelopmentCompleted"],["frontend-builder","backend","firebase"],"none",5760,3,180,["project_manager"],1440),rollbackStage:"development"},
 seo:d("seo",["developmentComplete"],["SEOCompleted"],["seo"],"none",1440,3,60,["project_manager"],360),
 qa:d("qa",["seoComplete"],["QACompleted","QAFailed"],["qa"],"none",1440,3,60,["project_manager"],480),
 customer_approval:d("customer_approval",["qaPassed"],["WebsiteApproved","ApprovalRejected"],["project-manager"],"customer",4320,5,240,["ceo","project_manager","customer"],1440),
 deployment:d("deployment",["websiteApproved"],["DeploymentCompleted"],["deployment"],"ceo",720,3,30,["ceo","project_manager"],180),
 maintenance:d("maintenance",["deploymentComplete"],["MaintenanceStarted"],["maintenance","analytics","support"],"none",43200,10,1440,["ceo","project_manager"],43200)
};
function d(stage:WorkflowStage,entryConditions:WorkflowCondition[],exitEvents:WorkflowEventType[],requiredAgents:AgentId[],approval:WorkflowStageDefinition["approval"],timeoutMinutes:number,maxAttempts:number,backoffMinutes:number,notifications:WorkflowStageDefinition["notifications"],estimatedMinutes:number):WorkflowStageDefinition{return{stage,entryConditions,exitEvents,requiredAgents,approval,timeoutMinutes,retry:{maxAttempts,backoffMinutes},notifications,estimatedMinutes}}
export const eventTransitions:Partial<Record<WorkflowEventType,{from:WorkflowStage[];to:WorkflowStage}>>={PhoneCallScheduled:{from:["lead"],to:"phone_call"},PhoneCallCompleted:{from:["phone_call"],to:"phone_call"},LeadWon:{from:["phone_call"],to:"won"},ProjectIntakeStarted:{from:["won"],to:"questionnaire"},QuestionnaireCompleted:{from:["questionnaire"],to:"assets"},AssetsUploaded:{from:["assets"],to:"assets"},AssetsValidated:{from:["assets"],to:"brand_strategy"},BrandApproved:{from:["brand_strategy"],to:"website_architecture"},ArchitectureCompleted:{from:["website_architecture"],to:"ui_design"},UIDesignApproved:{from:["ui_design"],to:"copywriting"},CopywritingCompleted:{from:["copywriting"],to:"development"},DevelopmentStarted:{from:["development"],to:"development"},DevelopmentCompleted:{from:["development"],to:"seo"},SEOCompleted:{from:["seo"],to:"qa"},QACompleted:{from:["qa"],to:"customer_approval"},QAFailed:{from:["qa"],to:"development"},WebsiteApproved:{from:["customer_approval"],to:"deployment"},ApprovalRejected:{from:["customer_approval"],to:"ui_design"},DeploymentCompleted:{from:["deployment"],to:"maintenance"},AssetsMissing:{from:["brand_strategy","website_architecture","ui_design","copywriting","development","seo","qa"],to:"assets"}};
export function nextWorkflowStage(stage:WorkflowStage){return workflowOrder[workflowOrder.indexOf(stage)+1]}
export function workflowProgress(stage:WorkflowStage){return Math.round(workflowOrder.indexOf(stage)/(workflowOrder.length-1)*100)}
export function resolveWorkflowTransition(stage:WorkflowStage,event:WorkflowEventType){if(event==="LeadCreated")return stage==="lead"?{from:stage,to:stage}:undefined;const transition=eventTransitions[event];return transition?.from.includes(stage)?{from:stage,to:transition.to}:undefined}
