"use client";
import {useState} from "react";
import {ref,uploadBytes} from "firebase/storage";
import {CheckCircle2,RotateCcw,UploadCloud} from "lucide-react";
import {type Project} from "@pageloom/core";
import {firebaseAuth,firebaseStorage} from "@/lib/firebase";
import {api} from "@/lib/api";
import {useOrganization} from "@/lib/organization";
import {useLiveCollection} from "@/lib/live-data";
import {Button,Card,Empty,PageHeader,Status} from "@/components/product-ui";

export default function Portal(){
  const{organizationId,membership}=useOrganization(),client=membership?.role==="client",projects=useLiveCollection<Project>(organizationId?`organizations/${organizationId}/projects`:undefined,"updatedAt",100,client?"customerId":undefined,client?membership.customerId:undefined);
  const[id,setId]=useState(""),[comment,setComment]=useState(""),[busy,setBusy]=useState(false),[message,setMessage]=useState(""),project=projects.data.find(item=>item.id===id)??projects.data[0];
  async function upload(event:React.ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0],uid=firebaseAuth.currentUser?.uid;if(!file||!uid||!project)return;setBusy(true);try{await uploadBytes(ref(firebaseStorage,`organizations/${organizationId}/uploads/${uid}/${project.id}/${crypto.randomUUID()}-${file.name}`),file,{contentType:file.type,customMetadata:{projectId:project.id,purpose:"customer-review"}});setMessage("File uploaded securely.")}finally{setBusy(false);event.target.value=""}}
  async function send(){if(!project||!comment.trim())return;setBusy(true);try{await api(`/projects/${project.id}/comments`,{method:"POST",body:JSON.stringify({organizationId,content:comment})});setComment("");setMessage("Your comment was sent to the project team.")}finally{setBusy(false)}}
  async function review(type:"CustomerApproved"|"CustomerRequestedRevision"){if(!project)return;setBusy(true);try{await api("/workflow/events",{method:"POST",body:JSON.stringify({organizationId,projectId:project.id,type,payload:{comment:comment.trim()||null}})});setComment("");setMessage(type==="CustomerApproved"?"Website approved. Final deployment now requires CEO approval.":"Revision request recorded and routed to the production team.")}finally{setBusy(false)}}
  return <div className="space-y-6"><PageHeader eyebrow="CUSTOMER EXPERIENCE" title="Client portal" description="Upload files, review progress, leave feedback, and approve your website from one secure workspace."/>{projects.error&&<Card><p className="text-[10px] text-[#a33]">{projects.error}</p></Card>}<Card><label className="field"><span>Project</span><select className="input" value={project?.id??""} onChange={event=>setId(event.target.value)}><option value="">Choose a project</option>{projects.data.map(item=><option value={item.id} key={item.id}>{item.name}</option>)}</select></label></Card>{project?<div className="grid gap-4 lg:grid-cols-2"><Card><div className="flex items-start justify-between"><div><h2 className="text-sm font-semibold">Project progress</h2><p className="mt-1 text-[9px] capitalize text-[var(--muted)]">{(project.workflowStage??project.journeyStage).replaceAll("_"," ")}</p></div><Status value={project.workflowStatus??project.status}/></div><b className="mt-5 block text-3xl">{project.progress}%</b><div className="progress mt-4"><i style={{width:`${project.progress}%`}}/></div>{project.blockedReason&&<p className="mt-4 rounded-lg bg-[#fff4e5] p-3 text-[9px] text-[#8d5d12]">{project.blockedReason}</p>}</Card><Card><h2 className="text-sm font-semibold">Upload project files</h2><p className="mt-2 text-[10px] text-[var(--muted)]">Brand files, photography, content, and review documents are stored inside your organization.</p><label className="button button-secondary mt-5 cursor-pointer justify-center"><UploadCloud className="h-4 w-4"/>Choose file<input className="hidden" type="file" disabled={busy} onChange={upload}/></label></Card><Card className="lg:col-span-2"><h2 className="text-sm font-semibold">Feedback and approval</h2><textarea className="input mt-4 min-h-28" value={comment} onChange={event=>setComment(event.target.value)} placeholder="Share precise feedback with the project team"/><div className="mt-3 flex flex-wrap gap-2"><Button variant="secondary" disabled={!comment.trim()||busy} onClick={send}>Send comment</Button>{project.workflowStage==="customer_review"&&<><Button variant="secondary" disabled={busy} onClick={()=>void review("CustomerRequestedRevision")}><RotateCcw className="h-4 w-4"/>Request revision</Button><Button disabled={busy} onClick={()=>void review("CustomerApproved")}><CheckCircle2 className="h-4 w-4"/>Approve website</Button></>}</div>{message&&<p className="mt-4 rounded-lg bg-[#eef8f1] p-3 text-[10px] text-[#387a55]">{message}</p>}</Card></div>:<Card><Empty title={projects.loading?"Loading projects":"No assigned projects"} description="Your organization administrator must assign your customer account to a project before it appears here."/></Card>}</div>
}
